from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views, views_bom as bom_api, views_cameras as cameras_api, \
    views_commercial as commercial, \
    views_cost as cost, \
    views_documents as docs, \
    views_hr as hr, views_imports as imports_api, views_leave as leave_api, \
    views_notify as notify_api, \
    views_petty_cash as petty, views_projects as projects, \
    views_payroll as payroll_api, views_quotes as quotes, \
    views_stock as stock, views_subcontract as subcontract_api, \
    views_tools as tools_api, views_transfers as transfers_api, \
    views_tracking as tracking_api, views_vessels as vessels_api, \
    views_vouchers as vouchers, \
    views_receivables as receivables_api, \
    views_onboarding as onboarding_api, \
    views_procurement_schedule as psched_api, \
    views_profile as profile_api, \
    views_meetings as meetings_api, \
    views_client_admin as client_admin, \
    views_bonds as bonds_api, \
    views_worker_mgmt as worker_api

router = DefaultRouter(trailing_slash=False)  # API surface per design §3
router.register("sites", views.SiteViewSet, basename="site")
router.register("users", views.UserViewSet, basename="user")
router.register(
    "manpower-categories", views.ManpowerCategoryViewSet, basename="manpowercategory"
)
router.register("holidays", views.HolidayViewSet, basename="holiday")
router.register("item-categories", views.ItemCategoryViewSet,
                basename="itemcategory")
router.register("items", views.ItemViewSet, basename="item")
router.register("suppliers", quotes.SupplierViewSet, basename="supplier")
router.register("employees", hr.EmployeeViewSet, basename="employee")

urlpatterns = [
    path("health", views.health, name="health"),
    path("auth/login", views.auth_login, name="auth-login"),
    path("auth/logout", views.auth_logout, name="auth-logout"),
    path("auth/change-password", views.auth_change_password,
         name="auth-change-password"),
    path("auth/me", views.auth_me, name="auth-me"),
    path("directory", views.user_directory, name="user-directory"),
    # Client Portal accounts — HO admin manages who logs into the portal.
    path("client-users", client_admin.client_users, name="client-users"),
    path("client-users/<int:pk>", client_admin.client_user_detail,
         name="client-user-detail"),
    path("client-users/<int:pk>/password", client_admin.client_user_password,
         name="client-user-password"),
    path("notifications", notify_api.notifications_list, name="notifications"),
    path("notifications/read", notify_api.notifications_read,
         name="notifications-read"),
    path("parameters/<str:key>", views.parameter_detail, name="parameter-detail"),
    path("company/logo", views.company_logo, name="company-logo"),
    path("company/stamp", views.company_stamp, name="company-stamp"),
    path("admin/login-activity", views.login_activity, name="login-activity"),
    path("admin/audit-trail", views.audit_trail, name="audit-trail"),
    path("pms", views.pm_list, name="pm-list"),
    path("cost-heads", views.cost_heads, name="cost-heads"),
    path("finance/awaiting-voucher", vouchers.awaiting_voucher,
         name="awaiting-voucher"),
    path("finance/payables", vouchers.payables, name="finance-payables"),
    path("finance/payables/<int:pk>/due-date", vouchers.payable_due_date,
         name="payable-due-date"),
    path("finance/dashboard", vouchers.finance_dashboard,
         name="finance-dashboard"),
    path("payment-vouchers", vouchers.payment_vouchers,
         name="payment-vouchers"),
    path("payment-vouchers/<str:ref>/pdf", vouchers.payment_voucher_pdf,
         name="payment-voucher-pdf"),
    path("payment-vouchers/<str:ref>", vouchers.payment_voucher_detail,
         name="payment-voucher-detail"),
    path("payment-vouchers/<str:ref>/actions/<str:action>",
         vouchers.payment_voucher_action, name="payment-voucher-action"),
    path("petty-cash/<int:site_id>", petty.petty_cash_float,
         name="petty-cash-float"),
    path("petty-cash/<int:site_id>/entries", petty.petty_cash_entries,
         name="petty-cash-entries"),
    path("petty-cash/<int:site_id>/entries/approve", petty.petty_cash_approve,
         name="petty-cash-approve"),
    path("petty-cash/<int:site_id>/replenish", petty.petty_cash_replenish,
         name="petty-cash-replenish"),
    path("petty-cash/<int:site_id>/reconcile", petty.petty_cash_reconcile,
         name="petty-cash-reconcile"),
    path("petty-cash/<int:site_id>/cycles", petty.petty_cash_cycles,
         name="petty-cash-cycles"),
    path("ipr", imports_api.ipr_list_create, name="ipr-list-create"),
    path("ipr/context", imports_api.ipr_context, name="ipr-context"),
    path("imports/tracker", imports_api.imports_tracker,
         name="imports-tracker"),
    path("pmr/register", imports_api.pmr_register, name="pmr-register"),
    path("ipr/<str:ref>/proforma", imports_api.ipr_proforma_upload,
         name="ipr-proforma"),
    path("ipr/payments-due", imports_api.ipr_payments_due,
         name="ipr-payments-due"),
    path("ipr/<str:ref>", imports_api.ipr_detail, name="ipr-detail"),
    path("ipr/<str:ref>/correct-charges", imports_api.ipr_correct_charges,
         name="ipr-correct-charges"),
    path("ipr/<str:ref>/correct-charges/decide",
         imports_api.ipr_correct_charges_decide,
         name="ipr-correct-charges-decide"),
    path("ipr/<str:ref>/milestones", imports_api.ipr_set_milestones,
         name="ipr-set-milestones"),
    path("ipr/<str:ref>/milestones/<int:pk>/due",
         imports_api.ipr_milestone_due, name="ipr-milestone-due"),
    path("ipr/<str:ref>/milestones/<int:pk>/pay",
         imports_api.ipr_milestone_pay, name="ipr-milestone-pay"),
    path("ipr/<str:ref>/milestones/<int:pk>/tt-advice",
         imports_api.ipr_milestone_tt_advice, name="ipr-milestone-tt-advice"),
    path("ipr/<str:ref>/shipments", imports_api.ipr_shipment_create,
         name="ipr-shipment-create"),
    path("ipr/<str:ref>/shipments/<int:pk>/status",
         imports_api.ipr_shipment_status, name="ipr-shipment-status"),
    path("ipr/<str:ref>/shipments/<int:pk>/update",
         imports_api.ipr_shipment_update, name="ipr-shipment-update"),
    path("ipr/<str:ref>/shipments/<int:pk>/delete",
         imports_api.ipr_shipment_delete, name="ipr-shipment-delete"),
    path("ipr/<str:ref>/shipments/<int:pk>/charges",
         imports_api.ipr_shipment_charges, name="ipr-shipment-charges"),
    path("ipr/<str:ref>/shipments/<int:pk>/payments/<str:kind>",
         imports_api.ipr_shipment_payment, name="ipr-shipment-payment"),
    path("ipr/<str:ref>/shipments/<int:pk>/payments/<str:kind>/raise",
         imports_api.ipr_shipment_payment_raise,
         name="ipr-shipment-payment-raise"),
    path("ipr/<str:ref>/shipments/<int:pk>/share",
         imports_api.ipr_shipment_share, name="ipr-shipment-share"),
    path("ipr/<str:ref>/shipments/<int:pk>/documents",
         imports_api.ipr_shipment_document, name="ipr-shipment-document"),
    path("ipr/<str:ref>/shipments/<int:pk>/receive",
         imports_api.ipr_shipment_receive, name="ipr-shipment-receive"),
    # --- shipment tracking (ShipsGo) ---
    path("vessels", vessels_api.vessels_list, name="vessels-list"),
    path("vessels/<str:vid>", vessels_api.vessel_detail, name="vessel-detail"),
    path("tracking/carriers", tracking_api.tracking_carriers,
         name="tracking-carriers"),
    path("tracking/carriers/refresh", tracking_api.tracking_carriers_refresh,
         name="tracking-carriers-refresh"),
    path("tracking/health", tracking_api.tracking_health,
         name="tracking-health"),
    path("tracking/shipments/<int:pk>/retry", tracking_api.tracking_retry,
         name="tracking-retry"),
    path("tracking/shipments/<int:pk>/manual", tracking_api.tracking_manual,
         name="tracking-manual"),
    path("store/lots", imports_api.store_lots, name="store-lots"),
    path("store/opening-stock", imports_api.store_opening_stock,
         name="store-opening-stock"),
    path("store/issues", imports_api.store_issues, name="store-issues"),
    path("sin/<str:ref>", imports_api.sin_detail, name="sin-detail"),
    path("sin/<str:ref>/issue", imports_api.sin_issue, name="sin-issue"),
    path("sin/<str:ref>/cancel", imports_api.sin_cancel, name="sin-cancel"),
    path("sin/<str:ref>/receive", imports_api.sin_receive, name="sin-receive"),
    path("mr/<str:ref>/store-availability", imports_api.mr_store_availability,
         name="mr-store-availability"),
    path("mr/<str:ref>/store-fulfil", imports_api.mr_store_fulfil,
         name="mr-store-fulfil"),
    path("irn/<str:ref>", imports_api.irn_detail, name="irn-detail"),
    path("irn/<str:ref>/counts", imports_api.irn_save_counts,
         name="irn-save-counts"),
    path("irn/<str:ref>/post", imports_api.irn_post, name="irn-post"),
    path("stock/<int:site_id>", stock.stock_balances, name="stock-balances"),
    path("stock/<int:site_id>/major", stock.stock_major_materials,
         name="stock-major-materials"),
    path("stock/<int:site_id>/major/<int:item_id>", stock.stock_set_major,
         name="stock-set-major"),
    path("stock/<int:site_id>/issue", stock.stock_issue, name="stock-issue"),
    path("stock/<int:site_id>/reconcile", stock.stock_reconcile,
         name="stock-reconcile"),
    path("stock/<int:site_id>/<int:item_id>/history", stock.stock_history,
         name="stock-history"),
    path("tool-catalog", tools_api.tool_catalog, name="tool-catalog"),
    path("tools/<int:site_id>", tools_api.tools_register,
         name="tools-register"),
    path("tools/<int:site_id>/summary", tools_api.tools_summary,
         name="tools-summary"),
    path("tools/asset/<int:pk>", tools_api.tool_detail, name="tool-detail"),
    path("tools/asset/<int:pk>/state", tools_api.tool_state,
         name="tool-state"),
    path("staff-cost/current", cost.staff_cost_current,
         name="staff-cost-current"),
    path("staff-cost/history", cost.staff_cost_history,
         name="staff-cost-history"),
    path("cost/portfolio", cost.cost_portfolio, name="cost-portfolio"),
    path("fx/usd-rate", cost.usd_rate, name="usd-rate"),
    path("cost/site/<int:site_id>", cost.site_cost, name="site-cost"),
    path("cost/site/<int:site_id>/postings", cost.site_cost_postings,
         name="site-cost-postings"),
    path("pm-overview", views.pm_overview, name="pm-overview"),
    path("dma-prefill", docs.dma_prefill, name="dma-prefill"),
    path("approvals/pending", docs.approvals_pending, name="approvals-pending"),
    path("documents", docs.document_create, name="document-create"),
    path("documents/list", docs.documents_list, name="documents-list"),
    path("documents/<str:ref>", docs.document_detail, name="document-detail"),
    path("documents/<str:ref>/actions/<str:action_name>", docs.document_action,
         name="document-action"),
    path("documents/<str:ref>/attachments", docs.document_attachments,
         name="document-attachments"),
    path("documents/<str:ref>/attachments/<int:pk>",
         docs.document_attachment_delete, name="document-attachment-delete"),
    path("documents/<str:ref>/edit-manifest", docs.lm_edit,
         name="lm-edit"),
    path("documents/<str:ref>/load-store", docs.lm_load_store,
         name="lm-load-store"),
    path("documents/<str:ref>/revisions", docs.document_revise,
         name="document-revise"),
    path("registers/dpr-tws", docs.register_dpr_tws, name="register-dpr-tws"),
    path("registers/<str:doc_type>", docs.register_generic,
         name="register-generic"),
    path("pending-items", docs.pending_items, name="pending-items"),
    path("pending-items/<int:pk>", docs.pending_items, name="pending-item"),
    path("mr/<str:ref>/export.xlsx", docs.mr_export, name="mr-export"),
    path("dpr/<str:ref>/report.pdf", docs.dpr_report_pdf, name="dpr-report-pdf"),
    path("mr/<str:ref>/lm-prefill", docs.mr_lm_prefill, name="mr-lm-prefill"),
    path("mr/<str:ref>/related", docs.mr_related, name="mr-related"),
    path("lm/<str:ref>/grn-prefill", docs.lm_grn_prefill, name="lm-grn-prefill"),
    path("po/<str:ref>/lm-prefill", docs.po_lm_prefill, name="po-lm-prefill"),
    path("pr/<str:ref>/quotations", quotes.pr_quotations, name="pr-quotations"),
    path("pr/<str:ref>/coverage", quotes.pr_coverage, name="pr-coverage"),
    path("pr/<str:ref>/release-lines", quotes.pr_release_lines,
         name="pr-release-lines"),
    path("pr/<str:ref>/sync-vendor-rows", quotes.pr_sync_vendor_rows,
         name="pr-sync-vendor-rows"),
    path("pr/<str:ref>/vendor-payment", quotes.pr_vendor_payment,
         name="pr-vendor-payment"),
    path("pr/<str:ref>/credit-terms", quotes.pr_credit_terms,
         name="pr-credit-terms"),
    path("quotations/<int:pk>", quotes.quotation_detail, name="quotation-detail"),
    path("quotations/<int:pk>/file", quotes.quotation_file,
         name="quotation-file"),
    path("dashboards/site/<int:site_id>", docs.dashboard_site,
         name="dashboard-site"),
    path("dashboards/ho", docs.dashboard_ho, name="dashboard-ho"),
    path("dashboards/hr", hr.dashboard_hr, name="dashboard-hr"),
    path("permits/alerts", hr.permit_alerts, name="permit-alerts"),
    path("permits/batch-renew", hr.permit_batch_renew,
         name="permit-batch-renew"),
    path("dashboards/portfolio", projects.dashboard_portfolio,
         name="dashboard-portfolio"),
    path("sites/summary", views.sites_summary, name="sites-summary"),
    path("transfers", transfers_api.transfer_list, name="transfer-list"),
    path("transfers/<int:pk>", transfers_api.transfer_action,
         name="transfer-action"),
    path("sites/<int:site_id>/transferable", transfers_api.transferable,
         name="transferable"),
    path("sites/<int:site_id>/projects", projects.site_projects,
         name="site-projects"),
    path("assignable/qs", projects.assignable_qs, name="assignable-qs"),
    path("projects/<int:pk>", projects.project_detail, name="project-detail"),
    path("projects/<int:pid>/bom", bom_api.bom_detail, name="bom-detail"),
    path("projects/<int:pid>/bom/save", bom_api.bom_save, name="bom-save"),
    path("projects/<int:pid>/bom/seed", bom_api.bom_seed, name="bom-seed"),
    path("projects/<int:pid>/bom/balance", bom_api.bom_balance,
         name="bom-balance"),
    path("projects/<int:pk>/programme", projects.project_programme,
         name="project-programme"),
    path("projects/<int:pk>/programme/capture", projects.programme_capture,
         name="programme-capture"),
    path("projects/<int:pk>/documents", projects.project_documents,
         name="project-documents"),
    path("projects/<int:pk>/programme.pdf", projects.programme_pdf,
         name="programme-pdf"),
    path("projects/<int:pk>/client-progress", projects.project_client_progress,
         name="project-client-progress"),
    path("programme-activities/<int:pk>", projects.activity_detail,
         name="activity-detail"),
    # Project commercial (QS) — BOQ
    path("projects/<int:pid>/boq", commercial.boq_detail, name="boq-detail"),
    path("projects/<int:pid>/boq/items", commercial.boq_save, name="boq-save"),
    path("projects/<int:pid>/boq/lock", commercial.boq_lock, name="boq-lock"),
    path("projects/<int:pid>/boq/claim-level", commercial.boq_claim_level,
         name="boq-claim-level"),
    path("projects/<int:pid>/boq/delete", commercial.boq_delete,
         name="boq-delete"),
    path("projects/<int:pid>/boq/import", commercial.boq_import,
         name="boq-import"),
    path("projects/<int:pid>/boq/template", commercial.boq_template,
         name="boq-template"),
    # Capture a BOQ from a client PDF/Excel → review draft → commit
    path("projects/<int:pid>/boq/capture-unit", commercial.boq_capture_unit,
         name="boq-capture-unit"),
    path("projects/<int:pid>/boq/commit-unit", commercial.boq_commit_unit,
         name="boq-commit-unit"),
    path("projects/<int:pid>/boq/categories/<int:cat_id>/items",
         commercial.boq_category_items, name="boq-category-items"),
    path("projects/<int:pid>/boq/capture", commercial.boq_import_extract,
         name="boq-capture"),
    path("projects/<int:pid>/boq/capture/draft", commercial.boq_import_latest,
         name="boq-capture-draft"),
    path("boq-imports/<int:pk>", commercial.boq_import_detail,
         name="boq-import-detail"),
    path("boq-imports/<int:pk>/commit", commercial.boq_import_commit,
         name="boq-import-commit"),
    path("projects/<int:pid>/variations", commercial.variation_list,
         name="variation-list"),
    path("projects/<int:pid>/variations/create", commercial.variation_create,
         name="variation-create"),
    path("variations/<int:pk>/items", commercial.variation_items,
         name="variation-items"),
    path("variations/<int:pk>/meta", commercial.variation_meta,
         name="variation-meta"),
    path("variations/<int:pk>/status", commercial.variation_status,
         name="variation-status"),
    # The client-facing variation order (P5-style PDF)
    path("variations/<int:pk>/vo.pdf", commercial.variation_pdf,
         name="variation-pdf"),
    path("variations/<int:pk>", commercial.variation_delete,
         name="variation-delete"),
    # Progress claims (interim payment applications / IPCs)
    path("projects/<int:pid>/claims", commercial.claim_list,
         name="claim-list"),
    path("projects/<int:pid>/claims/create", commercial.claim_create,
         name="claim-create"),
    path("claims/<int:pk>", commercial.claim_detail, name="claim-detail"),
    path("claims/<int:pk>/items", commercial.claim_items, name="claim-items"),
    path("claims/<int:pk>/meta", commercial.claim_meta, name="claim-meta"),
    path("claims/<int:pk>/deductions", commercial.claim_deductions,
         name="claim-deductions"),
    path("deduction-presets", commercial.deduction_presets,
         name="deduction-presets"),
    path("claims/<int:pk>/status", commercial.claim_status,
         name="claim-status"),
    path("claims/<int:pk>/delete", commercial.claim_delete,
         name="claim-delete"),
    # Bonds & insurance (APB / Performance / CAR / TPL)
    path("projects/<int:pid>/bonds", bonds_api.project_bonds,
         name="project-bonds"),
    path("project-bonds/<int:pk>", bonds_api.bond_detail, name="bond-detail"),
    path("project-bonds/<int:pk>/raise-pyr", bonds_api.bond_raise_pyr,
         name="bond-raise-pyr"),
    path("project-bonds/<int:pk>/issue", bonds_api.bond_issue,
         name="bond-issue"),
    path("project-bonds/<int:pk>/cancel", bonds_api.bond_cancel,
         name="bond-cancel"),
    path("projects/<int:pid>/receipts", commercial.receipt_create,
         name="receipt-create"),
    path("receipts/<int:pk>/delete", commercial.receipt_delete,
         name="receipt-delete"),
    path("claims/<int:pk>/ipa.pdf", commercial.claim_ipa_pdf,
         name="claim-ipa-pdf"),
    path("claims/<int:pk>/invoice.pdf", commercial.claim_invoice_pdf,
         name="claim-invoice-pdf"),
    # Receivables (Finance / QS / Director): aging + client statements
    path("receivables/aging", receivables_api.aging, name="rcv-aging"),
    path("receivables/clients", receivables_api.clients, name="rcv-clients"),
    path("receivables/invoices", receivables_api.invoices, name="rcv-invoices"),
    path("receivables/statement", receivables_api.statement,
         name="rcv-statement"),
    path("receivables/statement.pdf", receivables_api.statement_pdf,
         name="rcv-statement-pdf"),
    # Meetings — calendar / minutes / follow-up
    path("meetings", meetings_api.meetings, name="meetings"),
    path("meetings/my-actions", meetings_api.my_action_items,
         name="meeting-my-actions"),
    path("meetings/conflicts", meetings_api.meeting_conflicts,
         name="meeting-conflicts"),
    path("meetings/rsvp/<str:token>", meetings_api.meeting_rsvp,
         name="meeting-rsvp"),
    path("meeting-contacts", meetings_api.meeting_contacts,
         name="meeting-contacts"),
    path("meetings/<int:pk>", meetings_api.meeting_detail,
         name="meeting-detail"),
    path("meetings/<int:pk>/send-invite", meetings_api.meeting_send_invite,
         name="meeting-send-invite"),
    path("meetings/<int:pk>/send-minutes", meetings_api.meeting_send_minutes,
         name="meeting-send-minutes"),
    path("meetings/<int:pk>/files", meetings_api.meeting_files,
         name="meeting-files"),
    path("meetings/<int:pk>/files/<int:file_id>",
         meetings_api.meeting_file_item, name="meeting-file-item"),
    path("meetings/<int:pk>/actions", meetings_api.meeting_actions,
         name="meeting-actions"),
    path("meetings/<int:pk>/close", meetings_api.meeting_close,
         name="meeting-close"),
    path("meetings/<int:pk>/draft-minutes", meetings_api.meeting_draft_minutes,
         name="meeting-draft-minutes"),
    path("meetings/<int:pk>/minutes.pdf", meetings_api.meeting_minutes_pdf,
         name="meeting-minutes-pdf"),
    path("meetings/<int:pk>/reschedule", meetings_api.meeting_reschedule,
         name="meeting-reschedule"),
    path("meetings/<int:pk>/audio", meetings_api.meeting_audio,
         name="meeting-audio"),
    path("meetings/<int:pk>/audio/<int:audio_id>",
         meetings_api.meeting_audio_item, name="meeting-audio-item"),
    # Manual client invoices (historical + Planet-issued, off the claim flow)
    path("receivables/manual-invoices", receivables_api.manual_invoices,
         name="rcv-manual-invoices"),
    path("receivables/manual-invoices/<int:pk>/void",
         receivables_api.manual_invoice_void, name="rcv-manual-invoice-void"),
    path("receivables/manual-invoices/<int:pk>.pdf",
         receivables_api.manual_invoice_pdf, name="rcv-manual-invoice-pdf"),
    # Official receipts + the company bank accounts credited
    path("receivables/bank-accounts", receivables_api.bank_accounts,
         name="rcv-bank-accounts"),
    path("receivables/bank-accounts/<int:pk>",
         receivables_api.bank_account_detail, name="rcv-bank-account"),
    path("receivables/receipts", receivables_api.receipts, name="rcv-receipts"),
    path("receivables/receipts/<int:pk>", receivables_api.receipt_detail,
         name="rcv-receipt"),
    path("receivables/receipts/<int:pk>.pdf", receivables_api.receipt_pdf,
         name="rcv-receipt-pdf"),
    path("sites/<int:site_id>/manpower", hr.site_manpower,
         name="site-manpower"),
    path("employees/merge", hr.employee_merge, name="employee-merge"),
    path("employees/duplicate-passports", hr.duplicate_passports,
         name="duplicate-passports"),
    path("attendance", hr.attendance_grid, name="attendance-grid"),
    path("attendance/register", hr.attendance_register,
         name="attendance-register"),
    path("attendance/bulk", hr.attendance_bulk, name="attendance-bulk"),
    path("attendance/ot-approve", hr.ot_approve, name="ot-approve"),
    path("timesheets/<int:site_id>/<int:year>/<int:month>/lock",
         hr.timesheet_lock, name="timesheet-lock"),
    path("timesheets/<int:site_id>/<int:year>/<int:month>/reopen",
         hr.timesheet_reopen, name="timesheet-reopen"),
    path("payroll-export/<int:year>/<int:month>", hr.payroll_export,
         name="payroll-export"),
    path("overtime-rates", hr.overtime_rates, name="overtime-rates"),
    path("subcontractors", subcontract_api.subcontractors,
         name="subcontractors"),
    path("subcontractors/<int:pk>", subcontract_api.subcontractor_detail,
         name="subcontractor-detail"),
    path("subcontractors/<int:pk>/action", subcontract_api.subcontractor_action,
         name="subcontractor-action"),
    path("subcontractors/<int:pk>/workers",
         subcontract_api.subcontractor_workers, name="subcontractor-workers"),
    path("subcontract-workers/<int:emp_id>/action",
         subcontract_api.subcontract_worker_action, name="subcontract-worker"),
    path("subcontractors/<int:pk>/agreements",
         subcontract_api.subcontractor_agreements, name="sca-list"),
    path("subcontract-agreements", subcontract_api.site_agreements,
         name="sca-selectable"),
    path("subcontract-agreements/<str:ref>",
         subcontract_api.subcontract_agreement_edit, name="sca-edit"),
    path("subcontract-agreements/<str:ref>/pdf",
         subcontract_api.subcontract_agreement_pdf, name="sca-pdf"),
    path("subcontract-agreements/<str:ref>/valuations",
         subcontract_api.agreement_valuations, name="svc-list-create"),
    path("subcontract-valuations/<str:ref>",
         subcontract_api.valuation_detail, name="svc-detail"),
    path("subcontract-valuations/<str:ref>/action",
         subcontract_api.valuation_action, name="svc-action"),
    path("subcontract-valuations/<str:ref>/certificate.pdf",
         subcontract_api.valuation_certificate_pdf, name="svc-certificate"),
    # Site worker management (direct/salaried workforce) — approval batches
    path("worker-batches", worker_api.worker_batches, name="worker-batches"),
    path("worker-batches/<int:pk>/action", worker_api.batch_action,
         name="worker-batch-action"),
    path("sites/<int:site_id>/worker-batches", worker_api.create_batch,
         name="worker-batch-create"),
    path("sites/<int:site_id>/direct-workers",
         worker_api.site_direct_workers, name="site-direct-workers"),
    path("sites/<int:site_id>/transfer-destinations",
         worker_api.transfer_destinations, name="transfer-destinations"),
    path("worker-hires/<int:emp_id>", worker_api.hire_edit, name="hire-edit"),
    path("workers/<int:emp_id>/join-date", worker_api.worker_join_date,
         name="worker-join-date"),
    path("salary-revisions", worker_api.salary_revisions,
         name="salary-revisions"),
    path("salary-revisions/<int:pk>/action",
         worker_api.salary_revision_action, name="salary-revision-action"),
    # Onboarding cases (expat recruitment / visa / mobilisation)
    path("onboarding", onboarding_api.onboarding_cases, name="onboarding-cases"),
    path("onboarding/<int:pk>/hold", onboarding_api.onboarding_hold,
         name="onboarding-hold"),
    path("onboarding/bv-register", onboarding_api.onboarding_bv_register,
         name="onboarding-bv-register"),
    path("onboarding/passport-scan", onboarding_api.onboarding_passport_scan,
         name="onboarding-passport-scan"),
    path("onboarding/subcontractors", onboarding_api.onboarding_subcontractors,
         name="onboarding-subcontractors"),
    path("onboarding/<int:pk>/extend", onboarding_api.onboarding_extend,
         name="onboarding-extend"),
    path("onboarding/<int:pk>/close", onboarding_api.onboarding_close,
         name="onboarding-close"),
    path("sites/<int:site_id>/onboarding", onboarding_api.onboarding_create,
         name="onboarding-create"),
    path("onboarding/<int:pk>", onboarding_api.onboarding_detail,
         name="onboarding-detail"),
    path("onboarding/<int:pk>/submit", onboarding_api.onboarding_submit,
         name="onboarding-submit"),
    path("onboarding/<int:pk>/action", onboarding_api.onboarding_action,
         name="onboarding-action"),
    path("onboarding/<int:pk>/stage", onboarding_api.onboarding_stage,
         name="onboarding-stage"),
    path("onboarding/<int:pk>/stage-data", onboarding_api.onboarding_stage_data,
         name="onboarding-stage-data"),
    path("onboarding/<int:pk>/fee", onboarding_api.onboarding_fee,
         name="onboarding-fee"),
    path("onboarding/<int:pk>/stage-doc", onboarding_api.onboarding_stage_doc,
         name="onboarding-stage-doc"),
    path("onboarding/<int:pk>/attachments/<int:att_id>",
         onboarding_api.onboarding_attachment, name="onboarding-attachment"),
    path("onboarding/<int:pk>/letter", onboarding_api.onboarding_letter,
         name="onboarding-letter"),
    path("onboarding/<int:pk>/letters/<int:letter_id>.pdf",
         onboarding_api.onboarding_letter_download,
         name="onboarding-letter-download"),
    path("onboarding/letters/to-sign", onboarding_api.onboarding_letters_to_sign,
         name="onboarding-letters-to-sign"),
    path("onboarding/letters/<int:letter_id>/draft.pdf",
         onboarding_api.onboarding_letter_draft, name="onboarding-letter-draft"),
    path("onboarding/cases/<int:pk>/sign-off",
         onboarding_api.onboarding_case_sign_off, name="onboarding-case-signoff"),
    path("onboarding/my-stamp", onboarding_api.onboarding_my_stamp,
         name="onboarding-my-stamp"),
    path("onboarding/<int:pk>/documents", onboarding_api.onboarding_document,
         name="onboarding-document"),
    # --- procurement schedule (PSC) ---
    # Management, corporate info and the cover photo — all three used to be
    # hardcoded in the renderer (owner 2026-08-19)
    # Retiring a finished project into the references section, and back
    path("profile/entries/<int:pk>/complete", profile_api.profile_entry_complete,
         name="profile-entry-complete"),
    path("profile/entries/<int:pk>/reopen", profile_api.profile_entry_reopen,
         name="profile-entry-reopen"),
    path("profile/management", profile_api.profile_management,
         name="profile-management"),
    path("profile/management/<int:pk>", profile_api.profile_management_detail,
         name="profile-management-detail"),
    path("profile/management/<int:pk>/photo",
         profile_api.profile_management_photo, name="profile-management-photo"),
    path("profile/management/reorder", profile_api.profile_management_reorder,
         name="profile-management-reorder"),
    path("profile/corporate", profile_api.profile_corporate,
         name="profile-corporate"),
    path("profile/corporate/<int:pk>", profile_api.profile_corporate_detail,
         name="profile-corporate-detail"),
    path("profile/corporate/reorder", profile_api.profile_corporate_reorder,
         name="profile-corporate-reorder"),
    path("profile/settings", profile_api.profile_settings,
         name="profile-settings"),
    path("profile/cover", profile_api.profile_cover, name="profile-cover"),
    path("profile/referees", profile_api.profile_referees,
         name="profile-referees"),
    path("profile/referees/<int:pk>", profile_api.profile_referee,
         name="profile-referee"),
    path("profile/entries", profile_api.profile_entries,
         name="profile-entries"),
    path("profile/entries/reorder", profile_api.profile_reorder,
         name="profile-reorder"),
    path("profile/entries/<int:pk>", profile_api.profile_entry,
         name="profile-entry"),
    path("profile/entries/<int:pk>/featured", profile_api.profile_featured,
         name="profile-featured"),
    path("profile/entries/<int:pk>/gallery", profile_api.profile_gallery,
         name="profile-gallery"),
    path("profile/gallery/<int:gid>", profile_api.profile_gallery_delete,
         name="profile-gallery-delete"),
    path("profile/generate", profile_api.profile_generate,
         name="profile-generate"),
    path("procurement-schedules", psched_api.schedule_list,
         name="psched-list"),
    path("projects/<int:project_id>/procurement-schedule",
         psched_api.project_schedule, name="psched-project"),
    path("procurement-schedules/<int:pk>", psched_api.schedule_detail,
         name="psched-detail"),
    path("procurement-schedules/<int:pk>/seed-bom",
         psched_api.schedule_seed_bom, name="psc-seed-bom"),
    path("procurement-schedules/<int:pk>/lines", psched_api.schedule_lines,
         name="psched-lines"),
    path("procurement-schedules/<int:pk>/submit", psched_api.schedule_submit,
         name="psched-submit"),
    path("procurement-schedules/<int:pk>/action", psched_api.schedule_action,
         name="psched-action"),
    path("procurement-schedules/<int:pk>/reopen", psched_api.schedule_reopen,
         name="psched-reopen"),
    path("procurement-schedules/<int:pk>/export", psched_api.schedule_export,
         name="psched-export"),
    path("procurement-schedules/<int:pk>/share", psched_api.schedule_share,
         name="psched-share"),
    path("procurement-schedule-lines/<int:line_id>", psched_api.schedule_line,
         name="psched-line"),
    path("procurement-schedule-lines/<int:line_id>/cancel",
         psched_api.schedule_line_cancel, name="psched-line-cancel"),
    path("procurement-schedule-lines/<int:line_id>/link",
         psched_api.schedule_line_link, name="psched-line-link"),
    path("procurement-schedule-lines/<int:line_id>/candidates",
         psched_api.schedule_line_candidates, name="psched-line-candidates"),
    path("procurement-schedule-lines/<int:line_id>/production",
         psched_api.schedule_line_production, name="psched-line-production"),
    path("procurement-schedule-lines/<int:line_id>/split",
         psched_api.schedule_line_split, name="psched-line-split"),
    path("procurement-schedule-lines/<int:line_id>/image",
         psched_api.schedule_line_image, name="psched-line-image"),
    path("procurement-schedule-lines/<int:line_id>/client-update",
         psched_api.schedule_line_client_update, name="psched-line-client"),
    path("procurement-schedule-lines/<int:line_id>/raise-ipr",
         psched_api.schedule_line_raise_ipr, name="psched-line-raise-ipr"),
    path("procurement-schedule-lines/<int:line_id>/quotes",
         psched_api.schedule_line_quotes, name="psched-line-quotes"),
    path("procurement-schedule-lines/<int:line_id>/award",
         psched_api.schedule_line_award, name="psched-line-award"),
    path("procurement-schedule-quotes/<int:quote_id>",
         psched_api.schedule_line_quote, name="psched-quote"),
    # Worker leave — HR grants, the worker sits at Head Office, HR marks the
    # return (owner 2026-08-20)
    path("leaves", leave_api.leaves, name="leaves"),
    path("leaves/overdue", leave_api.leaves_overdue, name="leaves-overdue"),
    path("leaves/<int:pk>/return", leave_api.leave_return, name="leave-return"),
    path("leaves/<int:pk>/cancel", leave_api.leave_cancel, name="leave-cancel"),
    path("payroll/runs", payroll_api.payroll_runs, name="payroll-runs"),
    path("payroll/generate", payroll_api.payroll_generate,
         name="payroll-generate"),
    path("payroll/readiness", payroll_api.payroll_readiness,
         name="payroll-readiness"),
    path("payroll/attendance-summary", payroll_api.payroll_attendance_summary,
         name="payroll-attendance-summary"),
    path("payroll/ot-breakdown", payroll_api.payroll_ot_breakdown,
         name="payroll-ot-breakdown"),
    path("payroll/runs/<int:pk>", payroll_api.payroll_run_detail,
         name="payroll-run-detail"),
    path("payroll/runs/<int:pk>/report.pdf", payroll_api.payroll_report_pdf,
         name="payroll-report-pdf"),
    path("payroll/lines/<int:pk>", payroll_api.payroll_line,
         name="payroll-line"),
    path("payroll/lines/<int:pk>/rest-day",
         payroll_api.payroll_line_rest_day, name="payroll-line-rest-day"),
    path("payroll/lines/<int:pk>/exclude",
         payroll_api.payroll_line_exclude, name="payroll-line-exclude"),
    path("payroll/lines/<int:pk>/payslip.pdf", payroll_api.payslip_pdf,
         name="payroll-payslip-pdf"),
    # 80mm thermal receipt slips — one worker, or a whole run one page each
    path("payroll/lines/<int:pk>/slip-thermal.pdf",
         payroll_api.payslip_thermal_pdf, name="payroll-payslip-thermal"),
    path("payroll/runs/<int:pk>/slips-thermal.pdf",
         payroll_api.run_slips_thermal_pdf, name="payroll-run-slips-thermal"),
    # Ready-to-send ESC/POS — the office PCs need nothing installed to print it
    path("payroll/runs/<int:pk>/slips.escpos", payroll_api.run_slips_escpos,
         name="payroll-run-slips-escpos"),
    path("payroll/printer-tool.zip", payroll_api.printer_tool_zip,
         name="payroll-printer-tool"),
    path("payroll/lines/<int:pk>/slip.escpos", payroll_api.payslip_escpos,
         name="payroll-payslip-escpos"),
    # Amending an issued purchase order (owner 2026-08-13)
    path("documents/<str:ref>/amend", docs.po_amend, name="po-amend"),
    path("documents/<str:ref>/amend-decision", docs.po_amend_decision,
         name="po-amend-decision"),
    path("documents/<str:ref>/amendment", docs.po_amendment,
         name="po-amendment"),
    # --- site cameras (owner 2026-08-12)
    path("cameras", cameras_api.camera_list, name="camera-list"),
    path("cameras/<int:pk>", cameras_api.camera_detail, name="camera-detail"),
    path("cameras/<int:pk>/ticket", cameras_api.camera_ticket,
         name="camera-ticket"),
    path("", include(router.urls)),
]
