from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views, views_cost as cost, views_documents as docs, \
    views_hr as hr, views_imports as imports_api, views_petty_cash as petty, \
    views_projects as projects, views_payroll as payroll_api, \
    views_quotes as quotes, views_stock as stock, views_tools as tools_api, \
    views_vouchers as vouchers

router = DefaultRouter(trailing_slash=False)  # API surface per design §3
router.register("sites", views.SiteViewSet, basename="site")
router.register("users", views.UserViewSet, basename="user")
router.register(
    "manpower-categories", views.ManpowerCategoryViewSet, basename="manpowercategory"
)
router.register("holidays", views.HolidayViewSet, basename="holiday")
router.register("item-categories", views.ItemCategoryViewSet,
                basename="itemcategory")
router.register("items", views.ItemViewSet, basename="item")
router.register("suppliers", quotes.SupplierViewSet, basename="supplier")
router.register("employees", hr.EmployeeViewSet, basename="employee")

urlpatterns = [
    path("health", views.health, name="health"),
    path("auth/login", views.auth_login, name="auth-login"),
    path("auth/logout", views.auth_logout, name="auth-logout"),
    path("auth/change-password", views.auth_change_password,
         name="auth-change-password"),
    path("auth/me", views.auth_me, name="auth-me"),
    path("parameters/<str:key>", views.parameter_detail, name="parameter-detail"),
    path("company/logo", views.company_logo, name="company-logo"),
    path("pms", views.pm_list, name="pm-list"),
    path("cost-heads", views.cost_heads, name="cost-heads"),
    path("finance/awaiting-voucher", vouchers.awaiting_voucher,
         name="awaiting-voucher"),
    path("finance/dashboard", vouchers.finance_dashboard,
         name="finance-dashboard"),
    path("payment-vouchers", vouchers.payment_vouchers,
         name="payment-vouchers"),
    path("payment-vouchers/<str:ref>/pdf", vouchers.payment_voucher_pdf,
         name="payment-voucher-pdf"),
    path("payment-vouchers/<str:ref>", vouchers.payment_voucher_detail,
         name="payment-voucher-detail"),
    path("payment-vouchers/<str:ref>/actions/<str:action>",
         vouchers.payment_voucher_action, name="payment-voucher-action"),
    path("petty-cash/<int:site_id>", petty.petty_cash_float,
         name="petty-cash-float"),
    path("petty-cash/<int:site_id>/entries", petty.petty_cash_entries,
         name="petty-cash-entries"),
    path("petty-cash/<int:site_id>/entries/approve", petty.petty_cash_approve,
         name="petty-cash-approve"),
    path("petty-cash/<int:site_id>/replenish", petty.petty_cash_replenish,
         name="petty-cash-replenish"),
    path("petty-cash/<int:site_id>/reconcile", petty.petty_cash_reconcile,
         name="petty-cash-reconcile"),
    path("petty-cash/<int:site_id>/cycles", petty.petty_cash_cycles,
         name="petty-cash-cycles"),
    path("ipr", imports_api.ipr_list_create, name="ipr-list-create"),
    path("ipr/context", imports_api.ipr_context, name="ipr-context"),
    path("ipr/payments-due", imports_api.ipr_payments_due,
         name="ipr-payments-due"),
    path("ipr/<str:ref>", imports_api.ipr_detail, name="ipr-detail"),
    path("ipr/<str:ref>/milestones", imports_api.ipr_set_milestones,
         name="ipr-set-milestones"),
    path("ipr/<str:ref>/milestones/<int:pk>/due",
         imports_api.ipr_milestone_due, name="ipr-milestone-due"),
    path("ipr/<str:ref>/milestones/<int:pk>/pay",
         imports_api.ipr_milestone_pay, name="ipr-milestone-pay"),
    path("stock/<int:site_id>", stock.stock_balances, name="stock-balances"),
    path("stock/<int:site_id>/major", stock.stock_major_materials,
         name="stock-major-materials"),
    path("stock/<int:site_id>/major/<int:item_id>", stock.stock_set_major,
         name="stock-set-major"),
    path("stock/<int:site_id>/issue", stock.stock_issue, name="stock-issue"),
    path("stock/<int:site_id>/reconcile", stock.stock_reconcile,
         name="stock-reconcile"),
    path("stock/<int:site_id>/<int:item_id>/history", stock.stock_history,
         name="stock-history"),
    path("tool-catalog", tools_api.tool_catalog, name="tool-catalog"),
    path("tools/<int:site_id>", tools_api.tools_register,
         name="tools-register"),
    path("tools/<int:site_id>/summary", tools_api.tools_summary,
         name="tools-summary"),
    path("tools/asset/<int:pk>", tools_api.tool_detail, name="tool-detail"),
    path("tools/asset/<int:pk>/state", tools_api.tool_state,
         name="tool-state"),
    path("staff-cost/current", cost.staff_cost_current,
         name="staff-cost-current"),
    path("staff-cost/history", cost.staff_cost_history,
         name="staff-cost-history"),
    path("cost/portfolio", cost.cost_portfolio, name="cost-portfolio"),
    path("fx/usd-rate", cost.usd_rate, name="usd-rate"),
    path("cost/site/<int:site_id>", cost.site_cost, name="site-cost"),
    path("cost/site/<int:site_id>/postings", cost.site_cost_postings,
         name="site-cost-postings"),
    path("pm-overview", views.pm_overview, name="pm-overview"),
    path("dma-prefill", docs.dma_prefill, name="dma-prefill"),
    path("approvals/pending", docs.approvals_pending, name="approvals-pending"),
    path("documents", docs.document_create, name="document-create"),
    path("documents/list", docs.documents_list, name="documents-list"),
    path("documents/<str:ref>", docs.document_detail, name="document-detail"),
    path("documents/<str:ref>/actions/<str:action_name>", docs.document_action,
         name="document-action"),
    path("documents/<str:ref>/attachments", docs.document_attachments,
         name="document-attachments"),
    path("documents/<str:ref>/revisions", docs.document_revise,
         name="document-revise"),
    path("registers/dpr-tws", docs.register_dpr_tws, name="register-dpr-tws"),
    path("registers/<str:doc_type>", docs.register_generic,
         name="register-generic"),
    path("pending-items", docs.pending_items, name="pending-items"),
    path("pending-items/<int:pk>", docs.pending_items, name="pending-item"),
    path("mr/<str:ref>/lm-prefill", docs.mr_lm_prefill, name="mr-lm-prefill"),
    path("mr/<str:ref>/related", docs.mr_related, name="mr-related"),
    path("lm/<str:ref>/grn-prefill", docs.lm_grn_prefill, name="lm-grn-prefill"),
    path("po/<str:ref>/lm-prefill", docs.po_lm_prefill, name="po-lm-prefill"),
    path("pr/<str:ref>/quotations", quotes.pr_quotations, name="pr-quotations"),
    path("pr/<str:ref>/coverage", quotes.pr_coverage, name="pr-coverage"),
    path("pr/<str:ref>/sync-vendor-rows", quotes.pr_sync_vendor_rows,
         name="pr-sync-vendor-rows"),
    path("pr/<str:ref>/vendor-payment", quotes.pr_vendor_payment,
         name="pr-vendor-payment"),
    path("quotations/<int:pk>", quotes.quotation_detail, name="quotation-detail"),
    path("quotations/<int:pk>/file", quotes.quotation_file,
         name="quotation-file"),
    path("dashboards/site/<int:site_id>", docs.dashboard_site,
         name="dashboard-site"),
    path("dashboards/ho", docs.dashboard_ho, name="dashboard-ho"),
    path("dashboards/hr", hr.dashboard_hr, name="dashboard-hr"),
    path("permits/alerts", hr.permit_alerts, name="permit-alerts"),
    path("permits/batch-renew", hr.permit_batch_renew,
         name="permit-batch-renew"),
    path("dashboards/portfolio", projects.dashboard_portfolio,
         name="dashboard-portfolio"),
    path("sites/<int:site_id>/projects", projects.site_projects,
         name="site-projects"),
    path("assignable/qs", projects.assignable_qs, name="assignable-qs"),
    path("projects/<int:pk>", projects.project_detail, name="project-detail"),
    path("projects/<int:pk>/programme", projects.project_programme,
         name="project-programme"),
    path("projects/<int:pk>/documents", projects.project_documents,
         name="project-documents"),
    path("projects/<int:pk>/programme.pdf", projects.programme_pdf,
         name="programme-pdf"),
    path("programme-activities/<int:pk>", projects.activity_detail,
         name="activity-detail"),
    path("sites/<int:site_id>/manpower", hr.site_manpower,
         name="site-manpower"),
    path("attendance", hr.attendance_grid, name="attendance-grid"),
    path("attendance/register", hr.attendance_register,
         name="attendance-register"),
    path("attendance/bulk", hr.attendance_bulk, name="attendance-bulk"),
    path("attendance/ot-approve", hr.ot_approve, name="ot-approve"),
    path("timesheets/<int:site_id>/<int:year>/<int:month>/lock",
         hr.timesheet_lock, name="timesheet-lock"),
    path("timesheets/<int:site_id>/<int:year>/<int:month>/reopen",
         hr.timesheet_reopen, name="timesheet-reopen"),
    path("payroll-export/<int:year>/<int:month>", hr.payroll_export,
         name="payroll-export"),
    path("overtime-rates", hr.overtime_rates, name="overtime-rates"),
    path("payroll/runs", payroll_api.payroll_runs, name="payroll-runs"),
    path("payroll/generate", payroll_api.payroll_generate,
         name="payroll-generate"),
    path("payroll/readiness", payroll_api.payroll_readiness,
         name="payroll-readiness"),
    path("payroll/runs/<int:pk>", payroll_api.payroll_run_detail,
         name="payroll-run-detail"),
    path("payroll/runs/<int:pk>/report.pdf", payroll_api.payroll_report_pdf,
         name="payroll-report-pdf"),
    path("payroll/lines/<int:pk>", payroll_api.payroll_line,
         name="payroll-line"),
    path("payroll/lines/<int:pk>/payslip.pdf", payroll_api.payslip_pdf,
         name="payroll-payslip-pdf"),
    path("", include(router.urls)),
]
