"""Client Portal URL space (`/api/client/`) — the isolated external realm.
Only ClientUser tokens authenticate here; staff sessions never reach it."""
from django.urls import path

from . import views_client

urlpatterns = [
    path("auth/login", views_client.client_login, name="client-login"),
    path("auth/logout", views_client.client_logout, name="client-logout"),
    path("auth/change-password", views_client.client_change_password,
         name="client-change-password"),
    path("me", views_client.client_me, name="client-me"),
    path("sites", views_client.client_sites, name="client-portal-sites"),
    path("sites/<int:pk>", views_client.client_site, name="client-portal-site"),
    path("sites/<int:pk>/gallery", views_client.client_site_gallery,
         name="client-portal-gallery"),
    path("sites/<int:pk>/cameras", views_client.client_site_cameras,
         name="client-portal-cameras"),
    path("cameras/<int:pk>/ticket", views_client.client_camera_ticket,
         name="client-portal-camera-ticket"),
    path("submittals/<int:pk>/pdf", views_client.client_submittal_pdf,
         name="client-portal-submittal-pdf"),
    path("sites/<int:pk>/procurement", views_client.client_site_procurement,
         name="client-portal-site-procurement"),
    path("sites/<int:pk>/procurement.xlsx",
         views_client.client_site_procurement_xlsx,
         name="client-portal-site-procurement-xlsx"),
    path("projects/<int:pk>/programme.pdf",
         views_client.client_project_programme_pdf,
         name="client-portal-programme-pdf"),
    path("projects/<int:pk>/programme", views_client.client_project_programme,
         name="client-portal-programme"),
    path("projects/<int:pk>/units", views_client.client_project_units,
         name="client-portal-units"),
    path("projects/<int:pk>/procurement",
         views_client.client_project_procurement,
         name="client-portal-procurement"),
    path("projects/<int:pk>/procurement.xlsx",
         views_client.client_project_procurement_xlsx,
         name="client-portal-procurement-xlsx"),
    path("documents/<str:ref>.pdf", views_client.client_document_pdf,
         name="client-portal-document-pdf"),
    path("documents/<str:ref>", views_client.client_document,
         name="client-portal-document"),
]
