# Generated by Django 5.2.15 on 2026-07-07 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_documentrevision_document_current_revision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=10)),
                ('category', models.TextField(blank=True)),
                ('brand', models.TextField(blank=True)),
                ('spec_ref', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('free_text_desc', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('qty_required', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_to_order', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_loaded', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_pending', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_manifest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.CharField(blank=True, max_length=8)),
                ('urgent_reason', models.TextField(blank=True)),
                ('amount_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vendor', models.TextField(blank=True)),
                ('quotation_ref', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('is_changed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.documentrevision')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.item')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='PendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text_desc', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('qty_pending', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('action_next', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('cleared_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_lm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.item')),
                ('lm_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_items', to='core.documentline')),
                ('pr_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_items', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('MR_PR', 'MR→PR'), ('MR_LM', 'MR→LM'), ('PR_LM', 'PR→LM'), ('LM_GRN', 'LM→GRN'), ('IR_NCR', 'IR→NCR')], max_length=8)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_from', to='core.document')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_to', to='core.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_document', 'to_document', 'link_type'), name='uniq_document_link')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('item__isnull', False), models.Q(('free_text_desc', ''), _negated=True), _connector='OR'), name='line_item_or_free_text'),
        ),
    ]
