# Generated by Django 5.2.15 on 2026-07-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supplier_documentline_amount_documentline_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms_default',
        ),
    ]
