# Generated by Django 5.2.15 on 2026-07-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_supplier_payment_terms_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=10, unique=True)),
                ('full_name', models.TextField()),
                ('passport_no', models.TextField(blank=True)),
                ('nationality', models.TextField(blank=True)),
                ('basic_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_permit_no', models.TextField(blank=True)),
                ('work_permit_expiry', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.TextField(blank=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.manpowercategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSiteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_allocations', to='core.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_allocations', to='core.site')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('normal_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ot_requested', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('ot_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ot_approved_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICK', 'Sick'), ('LEAVE', 'Leave'), ('HALF_DAY', 'Half day')], default='PRESENT', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ot_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='core.site')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='core.employee')),
            ],
            options={
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'day'), name='uniq_attendance_day')],
            },
        ),
        migrations.CreateModel(
            name='TimesheetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_months', to='core.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'year', 'month'), name='uniq_timesheet_month')],
            },
        ),
    ]
