# Generated by Django 5.2.15 on 2026-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_employeesiteallocation_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
