# Generated by Django 5.2.15 on 2026-07-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='po_ref',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('ENCLOSURE', 'Enclosure'), ('QUOTATION', 'Quotation'), ('EVIDENCE', 'Evidence'), ('GENERATED_PDF', 'Generated PDF'), ('PAYMENT_SLIP', 'Payment slip / voucher')], max_length=20),
        ),
    ]
