# Generated by Django 5.2.15 on 2026-07-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_programmeactivity_document_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manpower_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pm_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='client_address',
            field=models.TextField(blank=True),
        ),
    ]
