# Generated by Django 5.2.15 on 2026-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeactivity',
            name='predecessors',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
