# Generated by Django 5.2.15 on 2026-07-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_programmeactivity_predecessors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manpower_plan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
