# Generated by Django 5.2.15 on 2026-07-08 13:47

from django.db import migrations, models

# Trade/discipline defaults + whatever categories existing items already use
DEFAULTS = ["Civil", "Structural", "MEP", "Finishes", "Marine", "General",
            "Consumables", "Tools & Equipment", "Safety", "Electrical",
            "Plumbing"]


def seed_categories(apps, schema_editor):
    ItemCategory = apps.get_model("core", "ItemCategory")
    Item = apps.get_model("core", "Item")
    names = list(DEFAULTS)
    for existing in (Item.objects.exclude(category="")
                     .values_list("category", flat=True).distinct()):
        if existing and existing not in names:
            names.append(existing)
    for order, name in enumerate(names, start=10):
        ItemCategory.objects.get_or_create(
            name=name, defaults={"sort_order": order})


def unseed(apps, schema_editor):
    apps.get_model("core", "ItemCategory").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_project_manpower_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_categories, unseed),
    ]
