# Generated by Django 5.2.15 on 2026-07-09 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# §6C.1 default cost heads + the three HO non-project pools
HEADS = ["Materials", "Labour & Staff", "Subcontract", "Plant & Equipment",
         "Transport & Freight", "Site Overheads", "Permits & Fees", "Other"]
POOLS = ["General Stock", "Foreign Exchange", "Stock Adjustment"]


def seed_cost_heads(apps, schema_editor):
    CostHead = apps.get_model("core", "CostHead")
    for order, name in enumerate(HEADS, start=10):
        CostHead.objects.get_or_create(
            name=name, defaults={"sort_order": order})
    for order, name in enumerate(POOLS, start=90):
        CostHead.objects.get_or_create(
            name=name, defaults={"sort_order": order, "is_pool": True})


def unseed_cost_heads(apps, schema_editor):
    apps.get_model("core", "CostHead").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_itemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_pool', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('SIGNATORY', 'Signatory (Executive Director)'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('ADMIN', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='CostPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('COMMITTED', 'Committed'), ('INCURRED', 'Incurred'), ('PAID', 'Paid')], max_length=10)),
                ('source', models.CharField(choices=[('PR', 'Pr'), ('PYR', 'Pyr'), ('PETTY_CASH', 'Petty Cash'), ('STAFF', 'Staff'), ('IPR', 'Ipr'), ('STORE_ISSUE', 'Store Issue'), ('FX', 'Fx'), ('STOCK_ADJ', 'Stock Adj')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('posted_on', models.DateField()),
                ('is_stock_pool', models.BooleanField(default=False)),
                ('staff_year', models.IntegerField(blank=True, null=True)),
                ('staff_month', models.IntegerField(blank=True, null=True)),
                ('work_package', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='core.costhead')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document')),
                ('document_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentline')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='core.costposting')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_postings', to='core.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'state', 'cost_head', 'posted_on'], name='core_costpo_site_id_9515bd_idx'), models.Index(fields=['document'], name='core_costpo_documen_872883_idx')],
            },
        ),
        migrations.RunPython(seed_cost_heads, unseed_cost_heads),
    ]
