# Generated by Django 5.2.15 on 2026-07-09 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_costhead_alter_user_role_costposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr')], max_length=3),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_request', serialize=False, to='core.document')),
                ('payment_type', models.CharField(choices=[('DIRECT', 'Direct payment'), ('ADVANCE', 'Advance'), ('REIMBURSEMENT', 'Reimbursement'), ('PETTY_CASH_REPLENISH', 'Petty cash replenishment')], default='DIRECT', max_length=24)),
                ('payee', models.TextField()),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='BANK', max_length=16)),
                ('payee_account', models.TextField(blank=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('urgent_reason', models.TextField(blank=True)),
                ('has_supporting_doc', models.BooleanField(default=False)),
                ('no_doc_reason', models.TextField(blank=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('authorise_note', models.TextField(blank=True)),
                ('authorised_under_threshold', models.BooleanField(default=False)),
                ('returned_reason', models.CharField(blank=True, max_length=24)),
                ('returned_note', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.TextField(blank=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_ref', models.TextField(blank=True)),
                ('variance_reason', models.TextField(blank=True)),
                ('is_settled', models.BooleanField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_note', models.TextField(blank=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='core.costhead')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
