# Generated by Django 5.2.15 on 2026-07-09 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_document_doc_type_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='cost_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.costhead'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='purchase_type',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField()),
                ('terms', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='OUTSTANDING', max_length=12)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('settled_ref', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='core.document')),
                ('document_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentline')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='core.site')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_date'], name='core_payabl_status_339c1c_idx')],
            },
        ),
    ]
