# Generated by Django 5.2.15 on 2026-07-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_documentline_cost_head_documentline_purchase_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv')], max_length=3),
        ),
        migrations.CreateModel(
            name='PaymentVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('INCLUDED', 'Included'), ('APPROVED', 'Approved'), ('QUERIED', 'Queried')], default='INCLUDED', max_length=10)),
                ('query_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines_as_source', to='core.document')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_lines', to='core.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voucher', 'source_document'), name='uniq_voucher_source')],
            },
        ),
    ]
