# Generated by Django 5.2.15 on 2026-07-09 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_document_doc_type_paymentvoucherline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.IntegerField()),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REQUESTED', 'Requested'), ('REPLENISHED', 'Replenished')], default='OPEN', max_length=12)),
                ('closing_float', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-cycle_no'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='petty_cash_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishments', to='core.pettycashcycle'),
        ),
        migrations.CreateModel(
            name='PettyCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee', models.TextField()),
                ('purpose', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='petty_cash/')),
                ('has_receipt', models.BooleanField(default=False)),
                ('no_receipt_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECORDED', 'Recorded'), ('APPROVED', 'Approved'), ('REIMBURSED', 'Reimbursed'), ('VOID', 'Void')], default='RECORDED', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_entries', to='core.costhead')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.pettycashcycle')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='costposting',
            name='petty_cash_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pettycashentry'),
        ),
        migrations.CreateModel(
            name='PettyCashFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imprest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trigger_pct', models.IntegerField(default=30)),
                ('per_txn_cap', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_floats', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash', to='core.site')),
            ],
        ),
        migrations.AddField(
            model_name='pettycashcycle',
            name='float',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='core.pettycashfloat'),
        ),
        migrations.CreateModel(
            name='PettyCashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recon_date', models.DateField()),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('explanation', models.TextField(blank=True)),
                ('is_handover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('float', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='core.pettycashfloat')),
                ('incoming_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('outgoing_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recon_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pettycashcycle',
            constraint=models.UniqueConstraint(fields=('float', 'cycle_no'), name='uniq_float_cycle'),
        ),
    ]
