# Generated by Django 5.2.15 on 2026-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='items/'),
        ),
    ]
