# Generated by Django 5.2.15 on 2026-07-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_is_major_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.documentline'),
        ),
    ]
