# Generated by Django 5.2.15 on 2026-07-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_attachment_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.CharField(default='MVR', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ot_applies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.CreateModel(
            name='OvertimeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_by_default', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_rates', to='core.manpowercategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'currency'), name='uniq_ot_rate')],
            },
        ),
    ]
