# Generated by Django 5.2.15 on 2026-07-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_currency_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ADVANCE', 'Advance'), ('LOAN', 'Loan')], default='ADVANCE', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('months', models.IntegerField(default=1)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='core.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='core.employee')),
            ],
        ),
    ]
