# Generated by Django 5.2.15 on 2026-07-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_salaryadvance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('working_days', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked')], default='DRAFT', max_length=8)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='core.site')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_worked', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fridays_worked', models.IntegerField(default=0)),
                ('ot_hours', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_to_site', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_to_office', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='core.employee')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.site')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.payrollrun')),
            ],
            options={
                'ordering': ['employee__emp_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('site', 'currency', 'year', 'month'), name='uniq_payroll_run'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='uniq_payroll_line'),
        ),
    ]
