# Generated by Django 5.2.15 on 2026-07-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='is_tool',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ToolAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField(blank=True)),
                ('serial_no', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('IN_USE', 'In use'), ('FAULTY', 'Faulty'), ('UNDER_REPAIR', 'Under repair'), ('RETIRED', 'Retired')], default='IN_USE', max_length=12)),
                ('state_note', models.TextField(blank=True)),
                ('state_changed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MOBILISATION', 'Mobilisation'), ('GRN', 'Received (GRN)'), ('MANUAL', 'Added manually')], default='MANUAL', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_assets', to='core.item')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='core.site')),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['site', 'state'], name='core_toolas_site_id_7cf6fc_idx')],
            },
        ),
    ]
