# Generated by Django 5.2.15 on 2026-07-12 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_itemcategory_is_tool_toolasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract')], default='PERMANENT', max_length=10),
        ),
        migrations.CreateModel(
            name='WorkPermitRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField()),
                ('previous_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField()),
                ('permit_no', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_renewals', to='core.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
