# Generated by Django 5.2.15 on 2026-07-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_employee_employment_type_workpermitrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpermitrenewal',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_renewals', to='core.document'),
        ),
        migrations.AddField(
            model_name='workpermitrenewal',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.CharField(choices=[('DIRECT', 'Direct payment'), ('ADVANCE', 'Advance'), ('REIMBURSEMENT', 'Reimbursement'), ('PETTY_CASH_REPLENISH', 'Petty cash replenishment'), ('PERMIT_RENEWAL', 'Work-permit renewal')], default='DIRECT', max_length=24),
        ),
    ]
