# Generated by Django 5.2.15 on 2026-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_workpermitrenewal_document_workpermitrenewal_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpermitrenewal',
            name='permit_no',
        ),
        migrations.AddField(
            model_name='workpermitrenewal',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workpermitrenewal',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpermitrenewal',
            name='new_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
