# Generated by Django 5.2.15 on 2026-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_workpermitrenewal_permit_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_guarantee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='advance_payment_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('LUMP_SUM', 'Lump sum'), ('REMEASUREMENT', 'Re-measurement'), ('COST_PLUS', 'Cost plus')], max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='defects_liability_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='insurance_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='liquidated_damages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='performance_bond_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price_escalation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='retention_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='retention_release_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('SIGNATORY', 'Signatory (Executive Director)'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('QS', 'Quantity Surveyor'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
