# Generated by Django 5.2.15 on 2026-07-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_project_advance_guarantee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qs_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('POTENTIAL', 'Potential'), ('AWARDED', 'Awarded'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
