# Generated by Django 5.2.15 on 2026-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_project_qs_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_provisional',
            field=models.BooleanField(default=False),
        ),
    ]
