# Generated by Django 5.2.15 on 2026-07-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_clear_provisional_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMajorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.item')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_materials', to='core.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'item'), name='uniq_site_major_material')],
            },
        ),
    ]
