# Generated by Django 5.2.15 on 2026-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitemajormaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='mar_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='documentline',
            name='spec',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('LOCAL', 'Local supplier'), ('INTERNATIONAL', 'International supplier'), ('FORWARDER', 'Freight forwarder'), ('CLEARING_AGENT', 'Clearing agent')], default='LOCAL', max_length=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_incoterm',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr')], max_length=3),
        ),
    ]
