# Generated by Django 5.2.15 on 2026-07-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_documentline_mar_ref_documentline_spec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr')], max_length=3),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='link_type',
            field=models.CharField(choices=[('MR_PR', 'MR→PR'), ('MR_LM', 'MR→LM'), ('PR_LM', 'PR→LM'), ('LM_GRN', 'LM→GRN'), ('IR_NCR', 'IR→NCR'), ('PR_PO', 'PR→PO'), ('PO_LM', 'PO→LM'), ('PMR_IPR', 'PMR→IPR')], max_length=8),
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('incoterm', models.CharField(blank=True, max_length=12)),
                ('loading_port', models.CharField(blank=True, max_length=60)),
                ('discharge_port', models.CharField(blank=True, max_length=60)),
                ('pi_ref', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_order', to='core.document')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('free_text_desc', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('spec', models.TextField(blank=True)),
                ('order_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.costhead')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.importorder')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='ImportAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_allocations', to='core.project')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.importorderline')),
            ],
        ),
        migrations.AddField(
            model_name='costposting',
            name='ipr_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.importorderline'),
        ),
    ]
