# Generated by Django 5.2.15 on 2026-07-13 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_document_doc_type_alter_documentlink_link_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('label', models.CharField(max_length=60)),
                ('trigger', models.CharField(choices=[('ADVANCE', 'Advance / on order (PI)'), ('BL', 'On shipping documents (B/L)'), ('ARRIVAL', 'On arrival'), ('DATE', 'By date'), ('BALANCE', 'Balance / other')], default='BALANCE', max_length=8)),
                ('percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DUE', 'Due'), ('PAID', 'Paid')], default='PENDING', max_length=8)),
                ('tt_ref', models.CharField(blank=True, max_length=60)),
                ('mvr_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.importorder')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='costposting',
            name='ipr_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.importpaymentmilestone'),
        ),
    ]
