# Generated by Django 5.2.15 on 2026-07-13 05:45

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_importpaymentmilestone_costposting_ipr_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpaymentmilestone',
            name='tt_advice',
            field=models.FileField(blank=True, null=True, upload_to='import-docs/tt/'),
        ),
        migrations.CreateModel(
            name='ImportShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('mode', models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air')], default='SEA', max_length=3)),
                ('forwarder_name', models.CharField(blank=True, max_length=120)),
                ('vessel_flight', models.CharField(blank=True, max_length=80)),
                ('container_awb', models.CharField(blank=True, max_length=80)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('tracking_ref', models.CharField(blank=True, max_length=80)),
                ('carrier_link', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived Malé'), ('UNDER_CLEARING', 'Under clearing'), ('CLEARED', 'Cleared')], default='BOOKED', max_length=14)),
                ('shared_with_agent_at', models.DateTimeField(blank=True, null=True)),
                ('customs_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('import_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('port_handling', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('agent_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('local_transport', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('forwarder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.supplier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.importorder')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('BL_AWB', 'Bill of Lading / AWB'), ('PACKING_LIST', 'Packing list'), ('COMMERCIAL_INVOICE', 'Commercial invoice'), ('COO', 'Certificate of origin'), ('INSURANCE', 'Insurance'), ('TEST_CERT', 'Test certificate'), ('PI', 'Proforma invoice'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=core.models.shipment_doc_path)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.importshipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
