# Generated by Django 5.2.15 on 2026-07-13 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_importpaymentmilestone_tt_advice_importshipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('doc_ref', models.CharField(blank=True, max_length=20)),
                ('doc_type', models.CharField(blank=True, max_length=3)),
                ('doc_status', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(default='approval', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('external_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='core_notifi_recipie_43dea6_idx')],
            },
        ),
    ]
