# Generated by Django 5.2.15 on 2026-07-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_user_notify_external_user_phone_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshipment',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn')], max_length=3),
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_receipt', to='core.document')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.importshipment')),
            ],
        ),
        migrations.CreateModel(
            name='ImportReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('damaged_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition_note', models.TextField(blank=True)),
                ('ipr_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='core.importorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.importreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text_desc', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_landed_cost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('received_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='core.item')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='core.project')),
                ('source_ipr_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.importorderline')),
                ('source_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.importreceipt')),
            ],
            options={
                'ordering': ['-received_date', 'id'],
            },
        ),
    ]
