# Generated by Django 5.2.15 on 2026-07-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_importshipment_freight_importshipment_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpaymentmilestone',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document'),
        ),
        migrations.AddField(
            model_name='paymentvoucherline',
            name='source_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='core.importpaymentmilestone'),
        ),
        migrations.AlterField(
            model_name='importpaymentmilestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DUE', 'Due'), ('AUTHORISED', 'Authorised'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentvoucherline',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines_as_source', to='core.document'),
        ),
        migrations.AddConstraint(
            model_name='paymentvoucherline',
            constraint=models.UniqueConstraint(fields=('voucher', 'source_milestone'), name='uniq_voucher_milestone'),
        ),
    ]
