# Generated by Django 5.2.15 on 2026-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_importpaymentmilestone_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='origin',
            field=models.CharField(default='SITE', max_length=8),
        ),
        migrations.AddField(
            model_name='paymentvoucherline',
            name='currency',
            field=models.CharField(default='MVR', max_length=3),
        ),
    ]
