# Generated by Django 5.2.15 on 2026-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_paymentrequest_fx_rate_paymentrequest_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='proforma_invoice',
            field=models.FileField(blank=True, null=True, upload_to='import-docs/pi/'),
        ),
    ]
