# Generated by Django 5.2.15 on 2026-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_stocklot_qty_in_transit_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
