# Generated by Django 5.2.15 on 2026-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_input_gst_cost_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='fulfil_source',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
