# Generated by Django 5.2.15 on 2026-07-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_documentline_fulfil_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='store_issue_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.storeissueline'),
        ),
        migrations.AddField(
            model_name='storeissueline',
            name='received_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
