# Generated by Django 5.2.15 on 2026-07-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_documentline_store_issue_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='origin_note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='source_ipr_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.importorderline'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='source_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.importreceipt'),
        ),
    ]
