# Generated by Django 5.2.15 on 2026-07-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_stocklot_origin_note_alter_stocklot_source_ipr_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='project_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
