# Generated by Django 5.2.15 on 2026-07-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ipr_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='core.importorderline')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.importshipment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shipment', 'ipr_line'), name='uniq_shipment_line')],
            },
        ),
    ]
