# Generated by Django 5.2.15 on 2026-07-15 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_importshipmentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boq', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('item_code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_heading', models.BooleanField(default=False)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.boq')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
