# Generated by Django 5.2.15 on 2026-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_boq_boqitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqitem',
            name='rate',
        ),
        migrations.AddField(
            model_name='boq',
            name='split_rates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='rate_install',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='rate_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
