# Generated by Django 5.2.15 on 2026-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_boqitem_rate_boq_split_rates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='credit_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
