# Generated by Django 5.2.15 on 2026-07-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_documentline_credit_days_supplier_credit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucherline',
            name='source_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='core.payable'),
        ),
        migrations.AddConstraint(
            model_name='paymentvoucherline',
            constraint=models.UniqueConstraint(fields=('voucher', 'source_payable'), name='uniq_voucher_payable'),
        ),
    ]
