# Generated by Django 5.2.15 on 2026-07-15 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_paymentvoucherline_source_payable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('ref', models.CharField(max_length=20)),
                ('title', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('ADDITION', 'Addition'), ('OMISSION', 'Omission')], default='ADDITION', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to client'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('ref_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='core.project')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='VariationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('item_code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('rate_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate_install', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_heading', models.BooleanField(default=False)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.variation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
