# Generated by Django 5.2.15 on 2026-07-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_variation_variationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='output_gst_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ProgressClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('ref', models.CharField(max_length=20)),
                ('claim_type', models.CharField(choices=[('ADVANCE', 'Advance payment'), ('INTERIM', 'Interim'), ('RELEASE', 'Retention release'), ('FINAL', 'Final account')], default='INTERIM', max_length=8)),
                ('basis', models.CharField(choices=[('PERCENT', '% complete'), ('MEASURED', 'Measured qty')], default='PERCENT', max_length=8)),
                ('work_done_upto', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CERTIFIED', 'Certified'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('advance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recovery_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retention_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('material_on_site', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('material_off_site', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('retention_released', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('note', models.TextField(blank=True)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.progressclaim')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.project')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='ProgressClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BOQ', 'BOQ'), ('VO', 'Variation')], max_length=3)),
                ('cumulative_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cumulative_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.boqitem')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.progressclaim')),
                ('variation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.variationitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='progressclaim',
            constraint=models.UniqueConstraint(fields=('project', 'seq'), name='uniq_claim_seq_per_project'),
        ),
    ]
