# Generated by Django 5.2.15 on 2026-07-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_project_output_gst_pct_progressclaim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='ordered_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_mr_lines', to='core.document'),
        ),
    ]
