# Generated by Django 5.2.15 on 2026-07-16 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_backfill_ordered_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('received_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='core.progressclaim')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
    ]
