# Generated by Django 5.2.15 on 2026-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_clientreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressclaim',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
