# Generated by Django 5.2.15 on 2026-07-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_progressclaim_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='void_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
