# Generated by Django 5.2.15 on 2026-07-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_document_void_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshipment',
            name='bl_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='carrier_scac',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air')], default='SEA', max_length=3)),
                ('provider', models.CharField(default='shipsgo', max_length=20)),
                ('carrier_scac', models.CharField(blank=True, max_length=8)),
                ('tracking_key', models.CharField(blank=True, max_length=80)),
                ('provider_tracking_id', models.CharField(blank=True, max_length=64)),
                ('provider_ref', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(choices=[('PENDING_REGISTRATION', 'Pending registration'), ('ACTIVE', 'Active'), ('ARRIVED', 'Arrived'), ('FAILED', 'Failed'), ('MANUAL', 'Manual')], default='PENDING_REGISTRATION', max_length=22)),
                ('raw_status', models.CharField(blank=True, max_length=20)),
                ('current_eta', models.DateTimeField(blank=True, null=True)),
                ('eta_initial', models.DateTimeField(blank=True, null=True)),
                ('map_url', models.CharField(blank=True, max_length=300)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('register_attempts', models.IntegerField(default=0)),
                ('credits_consumed', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='core.importshipment')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('DEPARTED', 'Departed origin'), ('TRANSSHIPMENT', 'Transshipment'), ('ARRIVED', 'Arrived Malé'), ('ETA_UPDATED', 'ETA updated'), ('OTHER', 'Other')], max_length=16)),
                ('provider_event_code', models.CharField(blank=True, max_length=16)),
                ('provider_event_id', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('vessel_flight', models.CharField(blank=True, max_length=120)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('eta_at_event', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('WEBHOOK', 'Webhook'), ('POLL', 'Poll'), ('MANUAL', 'Manual')], default='WEBHOOK', max_length=8)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.shipmenttracking')),
            ],
            options={
                'ordering': ['event_time', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_event_id__gt', '')), fields=('tracking', 'provider_event_id'), name='uniq_tracking_event')],
            },
        ),
    ]
