# Generated by Django 5.2.15 on 2026-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_importshipment_bl_no_importshipment_carrier_scac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='shipsgo', max_length=20)),
                ('scac', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'scac'), name='uniq_carrier_scac')],
            },
        ),
    ]
