# Generated by Django 5.2.15 on 2026-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_employee_engagement_type_subcontractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sub_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PM_APPROVED', 'PM approved'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='DRAFT', max_length=12),
        ),
    ]
