# Generated by Django 5.2.15 on 2026-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_document_doc_type_subcontractagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sub_extra_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
