# Generated by Django 5.2.15 on 2026-07-20 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_attendance_sub_extra_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkerChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ADD', 'Add worker'), ('REMOVE', 'Remove worker'), ('TRANSFER', 'Transfer worker')], max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PM_APPROVED', 'PM approved'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='core.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_requests', to='core.site')),
                ('to_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
