# Generated by Django 5.2.15 on 2026-07-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_employee_hire_pending_workerchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerchangerequest',
            name='employee',
        ),
        migrations.AlterField(
            model_name='workerchangerequest',
            name='kind',
            field=models.CharField(choices=[('ADD', 'Add workers'), ('REMOVE', 'Remove workers'), ('TRANSFER', 'Transfer workers')], max_length=10),
        ),
        migrations.CreateModel(
            name='WorkerChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_items', to='core.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.workerchangerequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
