# Generated by Django 5.2.15 on 2026-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_workerchangerequest_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='importorder',
            name='freight_handling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
