# Generated by Django 5.2.15 on 2026-07-23 17:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_importorder_discount_importorder_freight_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshipment',
            name='clearing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='shipping_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='ShipmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FREIGHT', 'Forwarding agent freight'), ('DO', 'Delivery-order charges'), ('PORT', 'Port charges'), ('DUTY', 'Import duty')], max_length=8)),
                ('payee_name', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('invoice', models.FileField(blank=True, null=True, upload_to=core.models.shipment_invoice_path)),
                ('invoice_ref', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.supplier')),
                ('pyr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_payments', to='core.document')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.importshipment')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('shipment', 'kind'), name='uniq_shipment_payment_kind')],
            },
        ),
    ]
