# Generated by Django 5.2.15 on 2026-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_importshipment_clearing_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_capitalized',
            field=models.BooleanField(default=False),
        ),
    ]
