# Generated by Django 5.2.15 on 2026-07-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_paymentrequest_is_capitalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressclaim',
            name='advance_recovered_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
