# Generated by Django 5.2.15 on 2026-07-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_progressclaim_advance_recovered_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('cumulative_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='core.progressclaim')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
