# Generated by Django 5.2.15 on 2026-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_deductionpreset_claimdeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_credit_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
