# Generated by Django 5.2.15 on 2026-07-24 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_bank_account(apps, schema_editor):
    """Seed the first bank account from the existing company_bank_* params so
    Finance has an 'account credited' to pick straight away."""
    CompanyParameter = apps.get_model("core", "CompanyParameter")
    CompanyBankAccount = apps.get_model("core", "CompanyBankAccount")

    def p(key):
        try:
            return CompanyParameter.objects.get(key=key).value or ""
        except CompanyParameter.DoesNotExist:
            return ""

    name = p("company_bank_name")
    acc_no = p("company_bank_account_no")
    if not (name or acc_no):
        return                          # nothing configured yet
    if CompanyBankAccount.objects.exists():
        return
    currency = p("company_bank_currency") or "USD"
    label = f"{name} {currency}".strip() or "Company account"
    CompanyBankAccount.objects.create(
        label=label, bank_name=name, branch=p("company_bank_branch"),
        account_name=p("company_bank_account_name"), account_no=acc_no,
        currency=currency, swift=p("company_bank_swift"),
        iban=p("company_bank_iban"), is_active=True, sort_order=0)


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_project_client_credit_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('account_no', models.CharField(blank=True, max_length=60)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('swift', models.CharField(blank=True, max_length=40)),
                ('iban', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfficialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('receipt_date', models.DateField()),
                ('method', models.CharField(choices=[('TT', 'Telegraphic transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], default='TT', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.companybankaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_receipts', to='core.site')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='official_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.officialreceipt'),
        ),
        migrations.RunPython(seed_bank_account, unseed),
    ]
