# Generated by Django 5.2.15 on 2026-07-24 15:47

from django.db import migrations, models


def mark_primary(apps, schema_editor):
    """The first active account becomes the invoice 'pay to' account."""
    CompanyBankAccount = apps.get_model("core", "CompanyBankAccount")
    first = CompanyBankAccount.objects.filter(is_active=True) \
        .order_by("sort_order", "id").first()
    if first:
        first.is_primary = True
        first.save(update_fields=["is_primary"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_companybankaccount_officialreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankaccount',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_primary, noop),
    ]
