# Generated by Django 5.2.15 on 2026-07-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_bankaccount_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.companybankaccount'),
        ),
    ]
