# Generated by Django 5.2.15 on 2026-07-25 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_document_debit_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], max_length=4)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Under review'), ('COMMITTED', 'Loaded into BOQ')], default='DRAFT', max_length=10)),
                ('rate_mode', models.CharField(blank=True, max_length=8)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_imports', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
