# Generated by Django 5.2.15 on 2026-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_boqimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client_tin',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
