# Generated by Django 5.2.15 on 2026-07-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_site_client_tin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_basic_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('to_basic_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('effective_month', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Awaiting Director'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='SUBMITTED', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='core.employee')),
                ('from_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.manpowercategory')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.site')),
                ('to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.manpowercategory')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
