# Generated by Django 5.2.15 on 2026-07-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_salary_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrevision',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Awaiting PM'), ('PM_APPROVED', 'Awaiting Director'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='SUBMITTED', max_length=12),
        ),
    ]
