# Generated by Django 5.2.15 on 2026-07-26 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_salary_revision_pm_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('ENCLOSURE', 'Enclosure'), ('QUOTATION', 'Quotation'), ('EVIDENCE', 'Evidence'), ('GENERATED_PDF', 'Generated PDF'), ('PAYMENT_SLIP', 'Payment slip / voucher'), ('PASSPORT_COPY', 'Passport copy'), ('PASSPORT_PHOTO', 'Passport photo'), ('PASSPORT_OBS', 'Passport observation page'), ('CV', 'CV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('OBR', 'Obr')], max_length=3),
        ),
        migrations.CreateModel(
            name='OnboardingCase',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding', serialize=False, to='core.document')),
                ('full_name', models.TextField()),
                ('nationality', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('passport_no', models.TextField(blank=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('SKILLED', 'Skilled'), ('UNSKILLED', 'Unskilled'), ('STAFF', 'Staff')], max_length=10)),
                ('trade_designation', models.TextField(blank=True)),
                ('proposed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('permanent_address', models.TextField(blank=True)),
                ('mobile', models.TextField(blank=True)),
                ('emergency_contact', models.TextField(blank=True)),
                ('mobilisation_date', models.DateField(blank=True, null=True)),
                ('route', models.CharField(choices=[('WP', 'Work permit (standard)'), ('BV', 'Business visa (urgent)')], max_length=2)),
                ('bv_justification', models.TextField(blank=True)),
                ('stage', models.CharField(blank=True, max_length=30)),
                ('arrived_date', models.DateField(blank=True, null=True)),
                ('medical_due', models.DateField(blank=True, null=True)),
                ('bv_expiry', models.DateField(blank=True, null=True)),
                ('bv_renewals', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.manpowercategory')),
            ],
        ),
    ]
