# Generated by Django 5.2.15 on 2026-07-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_onboarding_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='medical_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='portal_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
