# Generated by Django 5.2.15 on 2026-07-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_onboarding_stage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
                ('refundable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.onboardingcase')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_fee', to='core.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'stage'), name='uniq_onboarding_fee_per_stage')],
            },
        ),
    ]
