# Generated by Django 5.2.15 on 2026-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_onboardingletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='bv_alert',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='medical_alert',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
