# Generated by Django 5.2.15 on 2026-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_onboardingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='quota_pool',
            field=models.CharField(choices=[('SANDPLANET', 'Sand Planet'), ('MARINE', 'Sand Planet Marine')], default='SANDPLANET', max_length=12),
        ),
    ]
