# Generated by Django 5.2.15 on 2026-07-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_onboardingcase_quota_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='bv_purpose',
            field=models.CharField(blank=True, choices=[('RECRUITMENT', 'Recruitment (converts to work permit)'), ('SUBCONTRACT', "Subcontractor's worker")], max_length=12),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.subcontractor'),
        ),
    ]
