# Generated by Django 5.2.15 on 2026-07-26 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_onboardingcase_bv_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('OBR', 'Obr'), ('PSC', 'Psc')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProcurementSchedule',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='procurement_schedule', serialize=False, to='core.document')),
                ('baseline_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_schedule', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('sort_order', models.IntegerField(default=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.procurementschedule')),
            ],
            options={
                'ordering': ['sort_order', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('make_brand', models.CharField(blank=True, max_length=120)),
                ('specification', models.TextField(blank=True)),
                ('trade', models.CharField(blank=True, max_length=60)),
                ('supply_by', models.CharField(choices=[('CONTRACTOR', 'Contractor-supplied'), ('CLIENT', 'Client-supplied')], default='CONTRACTOR', max_length=12)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('tds_required', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('planned_supplier', models.CharField(blank=True, max_length=160)),
                ('source_country', models.CharField(blank=True, max_length=60)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('production_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PRODUCTION', 'In production'), ('COMPLETED', 'Completed')], default='PENDING', max_length=14)),
                ('client_last_update', models.DateField(blank=True, null=True)),
                ('client_update_note', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('SIGNED_OFF', 'Signed off'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('ipr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('mar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.procurementschedule')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.importshipment')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.schedulesection')),
            ],
            options={
                'ordering': ['section__sort_order', 'section__code', 's_no', 'id'],
            },
        ),
    ]
