# Generated by Django 5.2.15 on 2026-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_document_doc_type_procurementschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='uom',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
