# Generated by Django 5.2.15 on 2026-07-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_scheduleline_quantity_scheduleline_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.item'),
        ),
    ]
