# Generated by Django 5.2.15 on 2026-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_boqitem_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loa_ref',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
