# Generated by Django 5.2.15 on 2026-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_project_loa_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementschedule',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
