# Generated by Django 5.2.15 on 2026-07-28 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_procurementschedule_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='award_is_new_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='award_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScheduleLineQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=160)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('quoted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('quote_file', models.FileField(blank=True, null=True, upload_to='schedule-quotes/')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_awarded', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.scheduleline')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.supplier')),
            ],
            options={
                'ordering': ['-is_recommended', 'quoted_value', 'id'],
            },
        ),
    ]
