# Generated by Django 5.2.15 on 2026-07-29 04:55

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_scheduleline_award_is_new_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStaticAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COVER', 'Cover'), ('STORY', 'Story'), ('CORPORATE', 'Corporate'), ('DIVIDER_ONGOING', 'Divider — Ongoing'), ('DIVIDER_REFS', 'Divider — References'), ('REFEREES', 'Referees'), ('BACK', 'Back cover'), ('COMPLETED_LEGACY', 'Completed (legacy grid)')], max_length=20)),
                ('pdf', models.FileField(upload_to='profile/static/')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('SIGNATORY', 'Signatory (Executive Director)'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('QS', 'Quantity Surveyor'), ('ADMIN', 'Admin'), ('MARKETING', 'Marketing')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProfileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('project_name', models.TextField()),
                ('client_display', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('start_label', models.CharField(default='Commenced', max_length=20)),
                ('start_value', models.CharField(blank=True, max_length=80)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=core.models.profile_featured_path)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('snapshot_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.profile_gallery_path)),
                ('sort_order', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.profileentry')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
