# Generated by Django 5.2.15 on 2026-07-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_seed_profile_referees'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereferee',
            name='email',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
