# Generated by Django 5.2.15 on 2026-07-30 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_profilereferee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='mode',
            field=models.CharField(choices=[('CONVENTIONAL', 'Conventional (flat priced items)'), ('UNIT', 'Unit-based (per-unit prototype × quantity)')], default='CONVENTIONAL', max_length=14),
        ),
        migrations.CreateModel(
            name='BoqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('ref', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='no', max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_lump', models.BooleanField(default=False)),
                ('lump_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.boq')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='boqitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.boqcategory'),
        ),
    ]
