# Generated by Django 5.2.15 on 2026-07-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_boq_mode_boqcategory_boqitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressclaimitem',
            name='boq_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.boqcategory'),
        ),
        migrations.AlterField(
            model_name='progressclaimitem',
            name='source',
            field=models.CharField(choices=[('BOQ', 'BOQ'), ('VO', 'Variation'), ('CAT', 'Unit category')], max_length=3),
        ),
    ]
