# Generated by Django 5.2.15 on 2026-07-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_progressclaimitem_boq_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='bundle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
