# Generated by Django 5.2.15 on 2026-07-30 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_scheduleline_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('HISTORICAL', 'Historical (recorded)'), ('ISSUED', 'Issued on Planet')], max_length=10)),
                ('invoice_no', models.CharField(max_length=40)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='manual-invoices/')),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_invoices', to='core.project')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='manual_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='core.manualinvoice'),
        ),
    ]
