# Generated by Django 5.2.15 on 2026-08-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_manualinvoice_clientreceipt_manual_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoice',
            name='gst_pct',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.CreateModel(
            name='ManualInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.manualinvoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
