# Generated by Django 5.2.15 on 2026-08-01 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_manualinvoice_gst_pct_manualinvoiceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('PROJECT', 'Project review'), ('PROSPECT', 'Prospective client (BD)'), ('SITE', 'Site meeting'), ('OTHER', 'Other / internal')], max_length=10)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('org_contact', models.CharField(blank=True, max_length=160)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location_kind', models.CharField(choices=[('OFFICE', 'Head office'), ('SITE', 'At site'), ('CLIENT', "Client's office"), ('ONLINE', 'Online'), ('OTHER', 'Other')], default='OFFICE', max_length=8)),
                ('location_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('HELD', 'Held'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=10)),
                ('cadence', models.CharField(choices=[('ONE_OFF', 'One-off'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly')], default='ONE_OFF', max_length=12)),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('minutes_status', models.CharField(choices=[('NONE', 'No minutes yet'), ('DRAFT', 'Draft'), ('FINAL', 'Final')], default='NONE', max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_organised', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.project')),
                ('series_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='core.meeting')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.site')),
            ],
            options={
                'ordering': ['-scheduled_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carried_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.meetingactionitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='core.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('org', models.CharField(blank=True, max_length=160)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('is_external', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_external', 'id'],
            },
        ),
    ]
