# Generated by Django 5.2.15 on 2026-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_meeting_meetingactionitem_meetingattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqcategory',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
    ]
