# Generated by Django 5.2.15 on 2026-08-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_boqcategory_unit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('SIGNATORY', 'Signatory (Executive Director)'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('QS', 'Quantity Surveyor'), ('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('PA', "Personal Assistant — Director's Office")], max_length=20),
        ),
    ]
