# Generated by Django 5.2.15 on 2026-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractagreement',
            name='advance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='contractor_signatory_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='contractor_signatory_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='ld_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='ld_cap_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='payment_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='retention_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='scope_of_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='signatory_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='signatory_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
