# Generated by Django 5.2.15 on 2026-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_meetingaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
