# Generated by Django 5.2.15 on 2026-08-02 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_meeting_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costposting',
            name='source',
            field=models.CharField(choices=[('PR', 'Pr'), ('PYR', 'Pyr'), ('PETTY_CASH', 'Petty Cash'), ('STAFF', 'Staff'), ('IPR', 'Ipr'), ('STORE_ISSUE', 'Store Issue'), ('FX', 'Fx'), ('STOCK_ADJ', 'Stock Adj'), ('SUBCONTRACT', 'Subcontract')], max_length=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc')], max_length=3),
        ),
        migrations.CreateModel(
            name='SubcontractValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('work_done_upto', models.DateField(blank=True, null=True)),
                ('advance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retention_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deductions', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('adjustment', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('note', models.TextField(blank=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to='core.subcontractagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontract_valuation', to='core.document')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subcontractvaluation')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractValuationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('scope_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.subcontractscopeitem')),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.subcontractvaluation')),
            ],
            options={
                'ordering': ['scope_item__sort_order', 'id'],
            },
        ),
    ]
