# Generated by Django 5.2.15 on 2026-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_costposting_source_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
