# Generated by Django 5.2.15 on 2026-08-03 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_clientuser_clientsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
