# Generated by Django 5.2.15 on 2026-08-03 07:29

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_project_progress_note_project_progress_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('APB', 'Advance Payment Bond'), ('PB', 'Performance Bond'), ('CAR', "Contractor's All-Risk Insurance"), ('TPL', 'Third-Party Liability Insurance'), ('OTHER', 'Other cover')], max_length=8)),
                ('required', models.BooleanField(default=True)),
                ('insurer', models.TextField(blank=True)),
                ('insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('quote_ref', models.TextField(blank=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_file', models.FileField(blank=True, null=True, upload_to=core.models.bond_quote_path)),
                ('policy_ref', models.TextField(blank=True)),
                ('policy_file', models.FileField(blank=True, null=True, upload_to=core.models.bond_policy_path)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('QUOTED', 'Quoted'), ('PAYMENT_RAISED', 'Payment raised'), ('PAID', 'Premium paid'), ('ISSUED', 'Policy issued'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REQUIRED', max_length=16)),
                ('expiry_alert', models.CharField(blank=True, max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='core.project')),
                ('pyr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
    ]
