# Generated by Django 5.2.15 on 2026-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_projectbond'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='show_cameras',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='show_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='show_procurement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='show_programme',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='show_reports',
            field=models.BooleanField(default=True),
        ),
    ]
