# Generated by Django 5.2.15 on 2026-08-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_clientuser_show_cameras_clientuser_show_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='waived_stages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
