# Generated by Django 5.2.15 on 2026-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_onboardingcase_waived_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='allowances',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
