# Generated by Django 5.2.15 on 2026-08-04 11:10

from django.db import migrations, models


def flag_insurance_bonds(apps, schema_editor):
    # Existing "Insurance & Bonds" head becomes commercial so its PYRs route
    # to the Director (not the site PM). New heads default False.
    apps.get_model("core", "CostHead").objects.filter(
        name="Insurance & Bonds").update(commercial=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_onboardingcase_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='costhead',
            name='commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(flag_insurance_bonds, migrations.RunPython.noop),
    ]
