# Generated by Django 5.2.15 on 2026-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_costhead_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='origin',
            field=models.CharField(default='SITE', max_length=12),
        ),
    ]
