# Generated by Django 5.2.15 on 2026-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_scheduleline_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc')], max_length=3),
        ),
    ]
