# Generated by Django 5.2.15 on 2026-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_clientuser_show_submittals'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='old_passport_no',
            field=models.TextField(blank=True),
        ),
    ]
