# Generated by Django 5.2.15 on 2026-08-06 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_onboardingcase_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('LOGIN', 'Signed in'), ('FAILED', 'Failed sign-in'), ('LOGOUT', 'Signed out')], default='LOGIN', max_length=10)),
                ('source', models.CharField(default='WEB', max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['-at'], name='core_logine_at_39545f_idx'), models.Index(fields=['user', '-at'], name='core_logine_user_id_2c3f8c_idx')],
            },
        ),
    ]
