# Generated by Django 5.2.15 on 2026-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='misc_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
