# Generated by Django 5.2.15 on 2026-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_importorder_misc_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='usd_basic_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
