# Generated by Django 5.2.15 on 2026-08-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_meeting_ics_sequence_meeting_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='signatory_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='signatory_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
