# Generated by Django 5.2.15 on 2026-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_onboardingcase_signatory_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
