# Generated by Django 5.2.17 on 2026-08-10 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_user_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportChargeCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('freight_handling', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('misc_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_DIRECTOR', 'Awaiting Director'), ('PENDING_SIGNATORY', 'Awaiting Signatory'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PENDING_DIRECTOR', max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('director_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_corrections', to='core.importorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
