# Generated by Django 5.2.17 on 2026-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_importchargecorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchargecorrection',
            name='fold_line_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
