# Generated by Django 5.2.17 on 2026-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_importchargecorrection_fold_line_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqcategory',
            name='unit_amount_install',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='boqcategory',
            name='unit_amount_supply',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='progressclaimitem',
            name='cumulative_qty_install',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
