# Generated by Django 5.2.17 on 2026-08-11 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_boqcategory_unit_amount_install_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('source', models.CharField(choices=[('BOQ', 'Seeded from BOQ'), ('MANUAL', 'Manual')], default='MANUAL', max_length=6)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='core.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='core.project')),
            ],
            options={
                'ordering': ['item__code'],
                'constraints': [models.UniqueConstraint(fields=('project', 'item'), name='uniq_bom_project_item')],
            },
        ),
    ]
