# Generated by Django 5.2.17 on 2026-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_bomitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='claim_level',
            field=models.CharField(choices=[('CATEGORY', 'Per unit (summary categories)'), ('DETAIL', 'Per material (build-up quantities)')], default='CATEGORY', max_length=8),
        ),
    ]
