# Generated by Django 5.2.17 on 2026-08-12 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_payrollrun_approved_at_payrollrun_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('path', models.SlugField(max_length=40, unique=True)),
                ('stream_key', models.CharField(max_length=40)),
                ('location_note', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('client_visible', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core.site')),
            ],
            options={
                'ordering': ['site_id', 'name', 'id'],
            },
        ),
    ]
