# Generated by Django 5.2.17 on 2026-08-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
