# Generated by Django 5.2.17 on 2026-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_camera_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='rest_day_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
