# Generated by Django 5.2.17 on 2026-08-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_payrollline_rest_day_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='subcontract_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.subcontractagreement'),
        ),
    ]
