# Generated by Django 5.2.17 on 2026-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_paymentrequest_subcontract_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='excluded_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
