# Generated by Django 5.2.17 on 2026-08-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_payrollline_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='core.document'),
        ),
    ]
