# Generated by Django 5.2.17 on 2026-08-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_payrollrun_payment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressclaimitem',
            name='boq_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.boqcategory'),
        ),
        migrations.AlterField(
            model_name='progressclaimitem',
            name='boq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.boqitem'),
        ),
    ]
