# Generated by Django 5.2.17 on 2026-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_site_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='portal_ref',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
