# Generated by Django 5.2.17 on 2026-08-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_onboarding_portal_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='hold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='hold_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='stage_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
