# Generated by Django 5.2.17 on 2026-08-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_onboarding_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='portal_by_stage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
