# Generated by Django 5.2.17 on 2026-08-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_seed_profile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='cover_style',
            field=models.CharField(choices=[('BAND', 'Photo band with title below'), ('FULL', 'Full-bleed photo, title over it'), ('PANEL', 'Full-bleed photo with a title card')], default='FULL', max_length=6),
        ),
    ]
