# Generated by Django 5.2.17 on 2026-08-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_alter_profilesettings_cover_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='cover_style',
            field=models.CharField(choices=[('BAND', 'Photo band with title below'), ('FULL', 'Full-bleed photo, title over it'), ('TOP', 'Full-bleed photo, title at the top')], default='TOP', max_length=6),
        ),
    ]
