# Generated by Django 5.2.17 on 2026-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_cover_style_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='divider_focus',
            field=models.CharField(choices=[('LEFT', 'Left of the photo'), ('CENTER', 'Middle of the photo'), ('RIGHT', 'Right of the photo')], default='CENTER', max_length=6),
        ),
    ]
