# Generated by Django 5.2.17 on 2026-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_profile_copy_construction_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingletter',
            name='kind',
            field=models.CharField(max_length=12),
        ),
    ]
