# Generated by Django 5.2.17 on 2026-08-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_alter_onboardingletter_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccounter',
            name='doc_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='doc_type',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
