# Generated by Django 5.2.17 on 2026-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_alter_attendance_remark_workerleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingcase',
            name='bv_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
