# Generated by Django 5.2.17 on 2026-08-22 13:17

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_bv_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='employer_approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='employer_copy',
            field=models.FileField(blank=True, upload_to=core.models._variation_copy_path),
        ),
        migrations.AddField(
            model_name='variation',
            name='employer_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='variation',
            name='pd_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='pd_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variation',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PD_PENDING', 'With PD for approval'), ('PD_APPROVED', 'PD approved — ready to send'), ('SUBMITTED', 'Sent to Employer'), ('APPROVED', 'Approved by Employer'), ('REJECTED', 'Rejected by Employer')], default='DRAFT', max_length=12),
        ),
    ]
