# Generated by Django 5.2.17 on 2026-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_variation_two_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpaymentmilestone',
            name='credit_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importpaymentmilestone',
            name='fell_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importpaymentmilestone',
            name='pay_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
