# Generated by Django 5.2.17 on 2026-08-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_milestone_credit_and_pay_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('ref', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('scope', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('ON_HOLD', 'On hold')], default='NOT_STARTED', max_length=12)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('hold_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.boqcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnitStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.boqcategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnitStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitstage')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='core.projectunit')),
                ('updated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
            ],
            options={
                'ordering': ['stage__sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectunit',
            constraint=models.UniqueConstraint(fields=('project', 'ref'), name='uniq_project_unit_ref'),
        ),
        migrations.AddConstraint(
            model_name='unitstageprogress',
            constraint=models.UniqueConstraint(fields=('unit', 'stage'), name='uniq_unit_stage'),
        ),
    ]
