# Generated by Django 5.2.17 on 2026-08-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_project_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitstage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_stages', to='core.project'),
        ),
        migrations.AlterField(
            model_name='unitstage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.boqcategory'),
        ),
    ]
