# Generated by Django 5.2.17 on 2026-08-24 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_unit_stage_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('serial', models.CharField(max_length=40, unique=True)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('location_note', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_punch_at', models.DateTimeField(blank=True, null=True)),
                ('punches_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_devices', to='core.site')),
            ],
            options={
                'ordering': ['site_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=20)),
                ('finger_count', models.PositiveSmallIntegerField(default=0)),
                ('face_enrolled', models.BooleanField(default=False)),
                ('card_enrolled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrolments', to='core.employee')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.site')),
            ],
            options={
                'ordering': ['employee__emp_no'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device_user_id',), name='uniq_active_device_user_id')],
            },
        ),
        migrations.CreateModel(
            name='DevicePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(blank=True, max_length=20)),
                ('punched_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('UNKNOWN', 'Not stated')], default='UNKNOWN', max_length=8)),
                ('verify_mode', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched to a worker'), ('UNKNOWN_ID', 'No worker for this ID'), ('UNPARSED', 'Could not be read')], default='MATCHED', max_length=12)),
                ('raw', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='core.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_punches', to='core.employee')),
            ],
            options={
                'ordering': ['-punched_at', '-id'],
                'indexes': [models.Index(fields=['device', 'punched_at'], name='core_device_device__b29c6a_idx'), models.Index(fields=['employee', 'punched_at'], name='core_device_employe_e692a4_idx'), models.Index(fields=['status'], name='core_device_status_500c21_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'device_user_id', 'punched_at'), name='uniq_punch_per_device_user_time')],
            },
        ),
    ]
