# Generated by Django 5.2.17 on 2026-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_biometric_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='link_type',
            field=models.CharField(choices=[('MR_PR', 'MR→PR'), ('MR_LM', 'MR→LM'), ('PR_LM', 'PR→LM'), ('LM_GRN', 'LM→GRN'), ('IR_NCR', 'IR→NCR'), ('PR_PO', 'PR→PO'), ('PO_LM', 'PO→LM'), ('PMR_IPR', 'PMR→IPR'), ('IPR_CHARGE_PYR', 'IPR→charge PYR')], max_length=16),
        ),
    ]
