# Generated by Django 5.2.17 on 2026-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_alter_documentlink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_clearing_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_clearing_agent', True)), fields=('is_clearing_agent',), name='one_clearing_agent'),
        ),
    ]
