# Generated by Django 5.2.17 on 2026-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_supplier_is_clearing_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='late_after_min',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='site',
            name='ot_counts_from',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
