# Generated by Django 5.2.17 on 2026-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_siteshift_employeeshiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshipment',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
