# Generated by Django 5.2.17 on 2026-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_backfill_shipment_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='platform',
            field=models.CharField(choices=[('MOBILE', 'Planet Mobile'), ('DESKTOP', 'Planet Desktop')], default='MOBILE', max_length=8),
        ),
    ]
