# Generated by Django 5.2.17 on 2026-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_pushsubscription_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_cost',
            field=models.BooleanField(default=False),
        ),
    ]
