# Generated by Django 5.2.17 on 2026-08-29 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_document_shared_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeactivity',
            name='actual_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmeactivity',
            name='actual_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProgrammeBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_no', models.IntegerField()),
                ('label', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='core.project')),
            ],
            options={
                'ordering': ['project', '-rev_no'],
            },
        ),
        migrations.CreateModel(
            name='BaselineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('indent', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('match_key', models.CharField(db_index=True, max_length=200)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('is_milestone', models.BooleanField(default=False)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.programmebaseline')),
            ],
            options={
                'ordering': ['baseline', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='programmebaseline',
            constraint=models.UniqueConstraint(fields=('project', 'rev_no'), name='uniq_baseline_rev_per_project'),
        ),
    ]
