# Generated by Django 5.2.17 on 2026-08-29 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_programmeactivity_actual_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc')], max_length=3),
        ),
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NEAR_MISS', 'Near miss'), ('FIRST_AID', 'First aid'), ('MEDICAL', 'Medical treatment'), ('LOST_TIME', 'Lost-time injury'), ('FATALITY', 'Fatality'), ('PROPERTY', 'Property / plant damage'), ('ENVIRONMENTAL', 'Environmental'), ('DANGEROUS', 'Dangerous occurrence')], max_length=16)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=8)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('work_stopped', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_reportable', models.BooleanField(default=False)),
                ('reported_to_authority_on', models.DateField(blank=True, null=True)),
                ('authority_reference', models.CharField(blank=True, max_length=60)),
                ('investigation_started_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('contributing_factors', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_incident', to='core.document')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('employer', models.TextField(blank=True)),
                ('involvement', models.CharField(choices=[('INJURED', 'Injured'), ('INVOLVED', 'Involved'), ('WITNESS', 'Witness')], default='INVOLVED', max_length=10)),
                ('injury', models.TextField(blank=True)),
                ('body_part', models.CharField(blank=True, max_length=60)),
                ('treatment', models.TextField(blank=True)),
                ('days_lost', models.IntegerField(default=0)),
                ('returned_to_work_on', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.employee')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.safetyincident')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_preventive', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done — awaiting verification'), ('VERIFIED', 'Verified closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='core.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='core.site')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-priority'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='core_correc_status_8b76c3_idx')],
            },
        ),
    ]
