# Generated by Django 5.2.17 on 2026-08-29 11:04

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_alter_document_doc_type_safetyincident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt')], max_length=3),
        ),
        migrations.CreateModel(
            name='ToolboxTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('presenter_name', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField()),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('key_points', models.TextField(blank=True)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talk', to='core.document')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='PpeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=80)),
                ('qty', models.IntegerField(default=1)),
                ('issued_on', models.DateField()),
                ('replacement', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_issues', to='core.employee')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_issues', to='core.site')),
            ],
            options={
                'ordering': ['-issued_on'],
                'indexes': [models.Index(fields=['employee', 'issued_on'], name='core_ppeiss_employe_04d1e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyInduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inducted_on', models.DateField()),
                ('topics', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inductions', to='core.employee')),
                ('inducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inductions', to='core.site')),
            ],
            options={
                'ordering': ['-inducted_on'],
                'indexes': [models.Index(fields=['employee', 'site'], name='core_safety_employe_f09589_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolboxAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('employer', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.employee')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.toolboxtalk')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('talk', 'employee'), name='uniq_attendee_per_talk')],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PLANT', 'Plant / equipment operator'), ('HEIGHT', 'Working at height'), ('CONFINED', 'Confined space'), ('LIFTING', 'Lifting / rigging'), ('ELECTRICAL', 'Electrical'), ('HOT_WORK', 'Hot work'), ('FIRST_AID', 'First aid'), ('SCAFFOLD', 'Scaffolding'), ('DIVING', 'Diving / marine'), ('GENERAL', 'General safety')], default='GENERAL', max_length=12)),
                ('title', models.TextField()),
                ('issuer', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=core.models.training_cert_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_alert_stage', models.CharField(blank=True, max_length=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training', to='core.employee')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_on', 'employee'],
                'indexes': [models.Index(fields=['expires_on'], name='core_traini_expires_4a3a1b_idx')],
            },
        ),
    ]
