# Generated by Django 5.2.17 on 2026-08-29 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_alter_document_doc_type_toolboxtalk_ppeissue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt'), ('PTW', 'Ptw'), ('RAS', 'Ras'), ('HSI', 'Hsi')], max_length=3),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('assessed_on', models.DateField()),
                ('assessor_name', models.TextField(blank=True)),
                ('review_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='core.document')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.riskassessment')),
            ],
            options={
                'ordering': ['-assessed_on'],
            },
        ),
        migrations.CreateModel(
            name='RiskHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.TextField()),
                ('who_at_risk', models.TextField(blank=True)),
                ('existing_controls', models.TextField(blank=True)),
                ('likelihood', models.IntegerField(default=1)),
                ('severity', models.IntegerField(default=1)),
                ('rating', models.IntegerField(default=1)),
                ('band', models.CharField(blank=True, max_length=8)),
                ('further_controls', models.TextField(blank=True)),
                ('residual_likelihood', models.IntegerField(blank=True, null=True)),
                ('residual_severity', models.IntegerField(blank=True, null=True)),
                ('residual_rating', models.IntegerField(blank=True, null=True)),
                ('residual_band', models.CharField(blank=True, max_length=8)),
                ('sort_order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='core.riskassessment')),
            ],
            options={
                'ordering': ['assessment', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
                ('inspected_on', models.DateField()),
                ('inspector_name', models.TextField(blank=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_inspection', to='core.document')),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspected_on'],
            },
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('HOT_WORK', 'Hot work'), ('CONFINED', 'Confined space'), ('HEIGHT', 'Working at height'), ('LIFTING', 'Lifting operation'), ('EXCAVATION', 'Excavation'), ('ELECTRICAL', 'Electrical / isolation'), ('DIVING', 'Diving / marine'), ('OTHER', 'Other')], max_length=12)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('precautions', models.TextField(blank=True)),
                ('accepted_by_name', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_note', models.TextField(blank=True)),
                ('accepted_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.employee')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_permit', to='core.document')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
