# Generated by Django 5.2.17 on 2026-08-29 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_alter_document_doc_type_riskassessment_riskhazard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt'), ('PTW', 'Ptw'), ('RAS', 'Ras'), ('HSI', 'Hsi'), ('ITP', 'Itp'), ('NCR', 'Ncr')], max_length=3),
        ),
        migrations.CreateModel(
            name='InspectionTestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('discipline', models.CharField(blank=True, max_length=60)),
                ('prepared_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itp', to='core.document')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.inspectiontestplan')),
            ],
            options={
                'ordering': ['-prepared_on'],
            },
        ),
        migrations.CreateModel(
            name='ItpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('activity', models.TextField()),
                ('reference', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('point_type', models.CharField(choices=[('HOLD', 'Hold — work stops until signed'), ('WITNESS', 'Witness — invited to attend'), ('REVIEW', 'Review — records reviewed after'), ('MONITOR', 'Monitor — surveillance only')], default='REVIEW', max_length=8)),
                ('responsible', models.CharField(choices=[('US', 'Us'), ('CONSULTANT', 'Consultant'), ('CLIENT', 'Client'), ('THIRD_PARTY', 'Third party')], default='US', max_length=12)),
                ('frequency', models.CharField(blank=True, max_length=80)),
                ('record_required', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.inspectiontestplan')),
            ],
            options={
                'ordering': ['plan', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ItpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True)),
                ('inspected_on', models.DateField()),
                ('inspector_name', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'Not applicable')], max_length=4)),
                ('note', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itp_records', to='core.document')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.itpitem')),
            ],
            options={
                'ordering': ['-inspected_on'],
            },
        ),
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WORKMANSHIP', 'Workmanship'), ('MATERIAL', 'Material'), ('DOCUMENTATION', 'Documentation'), ('PROCESS', 'Process'), ('SUPPLIER', 'Supplier / subcontractor')], max_length=14)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=8)),
                ('raised_on', models.DateField()),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('requirement', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('REWORK', 'Rework to specification'), ('REPAIR', 'Repair'), ('USE_AS_IS', 'Use as is (concession)'), ('REGRADE', 'Re-grade / re-use elsewhere'), ('REJECT', 'Reject / remove')], max_length=10)),
                ('disposition_note', models.TextField(blank=True)),
                ('disposition_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disposition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ncr', to='core.document')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subcontract_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_ncrs', to='core.document')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='core.supplier')),
            ],
            options={
                'ordering': ['-raised_on'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quality', models.IntegerField(default=3)),
                ('delivery', models.IntegerField(default=3)),
                ('price', models.IntegerField(default=3)),
                ('responsiveness', models.IntegerField(default=3)),
                ('documentation', models.IntegerField(default=3)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('band', models.CharField(blank=True, max_length=12)),
                ('ncr_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.supplier')),
            ],
            options={
                'ordering': ['-period_end', 'supplier'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'period_start', 'period_end'), name='uniq_supplier_evaluation_period')],
            },
        ),
    ]
