# Generated by Django 5.2.17 on 2026-08-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_alter_document_doc_type_inspectiontestplan_itpitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notice_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rfi_response_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt'), ('PTW', 'Ptw'), ('RAS', 'Ras'), ('HSI', 'Hsi'), ('ITP', 'Itp'), ('NCR', 'Ncr'), ('RFI', 'Rfi'), ('LTR', 'Ltr'), ('INS', 'Ins'), ('NTC', 'Ntc'), ('DLY', 'Dly'), ('EOT', 'Eot')], max_length=3),
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RFI', 'Request for information'), ('LTR', 'Letter'), ('INS', 'Instruction'), ('NTC', 'Contractual notice')], max_length=4)),
                ('direction', models.CharField(choices=[('IN', 'Received'), ('OUT', 'Sent')], max_length=3)),
                ('party', models.CharField(choices=[('CLIENT', 'Client / Employer'), ('CONSULTANT', 'Consultant / Engineer'), ('SUBCONTRACTOR', 'Subcontractor'), ('SUPPLIER', 'Supplier'), ('AUTHORITY', 'Authority'), ('OTHER', 'Other')], default='CLIENT', max_length=14)),
                ('party_name', models.TextField(blank=True)),
                ('their_ref', models.CharField(blank=True, max_length=80)),
                ('subject', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('dated_on', models.DateField()),
                ('response_required', models.BooleanField(default=True)),
                ('response_due', models.DateField(blank=True, null=True)),
                ('responded_on', models.DateField(blank=True, null=True)),
                ('response_summary', models.TextField(blank=True)),
                ('clause', models.CharField(blank=True, max_length=80)),
                ('aware_on', models.DateField(blank=True, null=True)),
                ('time_bar_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='core.document')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('response_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
            ],
            options={
                'ordering': ['-dated_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DelayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('cause', models.CharField(choices=[('WEATHER', 'Weather / sea conditions'), ('LATE_INFORMATION', 'Information late'), ('INSTRUCTION', 'Instruction / variation'), ('ACCESS', 'Access not given'), ('LATE_MATERIAL', 'Material late'), ('SUBCONTRACTOR', 'Subcontractor'), ('AUTHORITY', 'Authority / permit'), ('OUR_OWN', 'Our own resource or method'), ('OTHER', 'Other')], max_length=17)),
                ('responsibility', models.CharField(choices=[('EMPLOYER', 'Employer risk'), ('CONTRACTOR', 'Our risk'), ('NEUTRAL', 'Neutral (shared)'), ('UNDECIDED', 'Not yet decided')], default='UNDECIDED', max_length=11)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('days_lost', models.IntegerField(blank=True, null=True)),
                ('mitigation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='delay_events', to='core.programmeactivity')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delay_event', to='core.document')),
                ('evidence', models.ManyToManyField(blank=True, related_name='evidences_delays', to='core.document')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_events', to='core.correspondence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delay_events', to='core.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionOfTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_claimed', models.IntegerField(default=0)),
                ('days_awarded', models.IntegerField(blank=True, null=True)),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('revised_completion', models.DateField(blank=True, null=True)),
                ('grounds', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.programmebaseline')),
                ('delay_events', models.ManyToManyField(blank=True, related_name='eot_applications', to='core.delayevent')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eot', to='core.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eot_applications', to='core.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['kind', 'response_due'], name='core_corres_kind_3a911a_idx'),
        ),
    ]
