# Generated by Django 5.2.17 on 2026-08-29 12:08

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_project_notice_period_days_project_rfi_response_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taking_over_on', models.DateField(blank=True, null=True)),
                ('taking_over_ref', models.CharField(blank=True, max_length=60)),
                ('making_good_on', models.DateField(blank=True, null=True)),
                ('making_good_ref', models.CharField(blank=True, max_length=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('AS_BUILT', 'As-built drawings'), ('INSPECTION', 'Inspection requests & checklists'), ('TEST', 'Test & commissioning records'), ('SUBMITTAL', 'Approved material submittals'), ('OM_MANUAL', 'O&M manuals'), ('WARRANTY', 'Warranties & guarantees'), ('CERTIFICATE', 'Statutory & authority certificates'), ('TRAINING', 'Client training records'), ('SPARES', 'Spares & attic stock'), ('OTHER', 'Other')], max_length=12)),
                ('discipline', models.CharField(choices=[('CIVIL', 'Civil / structural'), ('MEP', 'MEP'), ('FINISHES', 'Finishes'), ('EXTERNAL', 'External works'), ('GENERAL', 'General')], default='GENERAL', max_length=9)),
                ('title', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required — not yet provided'), ('PROVIDED', 'Provided'), ('ACCEPTED', 'Accepted by the client'), ('REJECTED', 'Returned for correction'), ('NOT_APPLICABLE', 'Not applicable')], default='REQUIRED', max_length=14)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.handover_file_path)),
                ('provided_on', models.DateField(blank=True, null=True)),
                ('accepted_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_items', to='core.document')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.handoverdossier')),
                ('provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dossier', 'section', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['dossier', 'section'], name='core_handov_dossier_fd2e1d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('dossier', 'document'), name='uniq_handover_document_per_dossier')],
            },
        ),
        migrations.CreateModel(
            name='SnagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('discipline', models.CharField(choices=[('CIVIL', 'Civil / structural'), ('MEP', 'MEP'), ('FINISHES', 'Finishes'), ('EXTERNAL', 'External works'), ('GENERAL', 'General')], default='GENERAL', max_length=9)),
                ('description', models.TextField()),
                ('raised_on', models.DateField()),
                ('owner_note', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('FIXED', 'Fixed — awaiting check'), ('CLOSED', 'Closed'), ('REJECTED', 'Not accepted as a defect')], default='OPEN', max_length=12)),
                ('photo', models.FileField(blank=True, null=True, upload_to=core.models.handover_file_path)),
                ('fixed_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('in_dlp', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snags', to='core.handoverdossier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snags', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dossier', 'status', 'due_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dossier', 'ref_no'), name='uniq_snag_ref_per_dossier')],
            },
        ),
    ]
