# Generated by Django 5.2.17 on 2026-08-29 12:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_handoverdossier_handoveritem_snagitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt'), ('PTW', 'Ptw'), ('RAS', 'Ras'), ('HSI', 'Hsi'), ('ITP', 'Itp'), ('NCR', 'Ncr'), ('RFI', 'Rfi'), ('LTR', 'Ltr'), ('INS', 'Ins'), ('NTC', 'Ntc'), ('DLY', 'Dly'), ('EOT', 'Eot'), ('TR', 'Tr')], max_length=3),
        ),
        migrations.CreateModel(
            name='MaterialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CUBE', 'Concrete cube (compressive strength)'), ('SLUMP', 'Slump / workability'), ('CORE', 'Concrete core'), ('COMPACTION', 'Compaction / field density'), ('CBR', 'CBR / bearing'), ('SIEVE', 'Sieve / grading'), ('STEEL', 'Steel tensile / bend'), ('PRESSURE', 'Pressure / leak test'), ('WATER', 'Water quality'), ('OTHER', 'Other')], max_length=10)),
                ('element', models.TextField()),
                ('location', models.TextField(blank=True)),
                ('pour_ref', models.CharField(blank=True, max_length=60)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('quantity', models.CharField(blank=True, max_length=60)),
                ('spec_reference', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('required_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('sampled_on', models.DateField()),
                ('lab_name', models.TextField(blank=True)),
                ('witnessed_by', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_test', to='core.document')),
                ('itp_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_tests', to='core.itpitem')),
                ('ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_tests', to='core.document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sampled_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_ref', models.CharField(blank=True, max_length=80)),
                ('specimen_ref', models.CharField(blank=True, max_length=60)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('tested_on', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Awaited')], default='PENDING', max_length=7)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=core.models.test_certificate_path)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.materialtest')),
            ],
            options={
                'ordering': ['test', 'age_days', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='materialtest',
            index=models.Index(fields=['kind', 'sampled_on'], name='core_materi_kind_65aa8a_idx'),
        ),
    ]
