# Generated by Django 5.2.17 on 2026-08-29 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_alter_document_doc_type_materialtest_testresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtest',
            options={'ordering': ['-requested_on', '-id']},
        ),
        migrations.AddField(
            model_name='materialtest',
            name='requested_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='materialtest',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialtest',
            name='sampled_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='materialtest',
            name='sampled_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
