# Generated by Django 5.2.17 on 2026-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_alter_materialtest_options_materialtest_requested_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='clearance_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='inspection_done_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='inspection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='inspection_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='shipping_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
