# Generated by Django 5.2.17 on 2026-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_scheduleline_clearance_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='order_by_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
