# Generated by Django 5.2.17 on 2026-08-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_scheduleline_order_by_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentpayment',
            options={'ordering': ['kind', 'created_at', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='shipmentpayment',
            name='uniq_shipment_payment_kind',
        ),
        migrations.AddField(
            model_name='shipmentpayment',
            name='label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
