# Generated by Django 5.2.17 on 2026-08-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtest',
            name='mix_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_from_mix', to='core.document'),
        ),
    ]
