# Generated by Django 5.2.17 on 2026-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_materialtest_mix_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt'), ('PTW', 'Ptw'), ('RAS', 'Ras'), ('HSI', 'Hsi'), ('ITP', 'Itp'), ('NCR', 'Ncr'), ('RFI', 'Rfi'), ('LTR', 'Ltr'), ('INS', 'Ins'), ('NTC', 'Ntc'), ('DLY', 'Dly'), ('EOT', 'Eot'), ('TR', 'Tr'), ('MXD', 'Mxd'), ('BBS', 'Bbs'), ('TWD', 'Twd'), ('MOC', 'Moc')], max_length=3),
        ),
    ]
