# Generated by Django 5.2.17 on 2026-08-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_alter_document_doc_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollrun',
            name='uniq_payroll_run',
        ),
        migrations.AddField(
            model_name='employee',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='left_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='kind',
            field=models.CharField(choices=[('MONTHLY', 'Monthly run'), ('SETTLEMENT', 'Final settlement')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='settlement_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'MONTHLY')), fields=('site', 'currency', 'year', 'month'), name='uniq_payroll_run'),
        ),
    ]
