# Generated by Django 5.2.17 on 2026-08-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_remove_payrollrun_uniq_payroll_run_employee_left_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='core.employee'),
        ),
    ]
