# Generated by Django 5.2.17 on 2026-08-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_user_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
