# Generated by Django 5.2.17 on 2026-08-30 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_user_salary_pin_user_salary_pin_set_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ADVANCE', 'Salary advance'), ('LEAVE_ANNUAL', 'Annual leave'), ('LEAVE_EMERGENCY', 'Emergency leave')], max_length=16)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Waiting for the Director'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('DONE', 'Done'), ('CANCELLED', 'Withdrawn')], default='SUBMITTED', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_requests', to='core.employee')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_requests', to='core.document')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.workerleave')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
