# Generated by Django 5.2.17 on 2026-08-31 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_staffrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitstage')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='core.projectunit')),
            ],
            options={
                'ordering': ['on', 'id'],
                'indexes': [models.Index(fields=['unit', 'on'], name='core_unitpr_unit_id_e4444a_idx')],
            },
        ),
    ]
