# Generated by Django 5.2.17 on 2026-08-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_unitprogressevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='delivered_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='delivered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
