# Generated by Django 5.2.17 on 2026-09-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_scheduleline_delivered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucherline',
            name='source_note',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
