# Generated by Django 5.2.17 on 2026-09-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_paymentvoucherline_source_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoice',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualinvoice',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_invoices', to='core.progressclaim'),
        ),
    ]
