# Generated by Django 5.2.17 on 2026-09-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_manualinvoice_superseded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='currency',
        ),
    ]
