# Generated by Django 5.2.17 on 2026-09-02 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_statuses(apps, schema_editor):
    """PROVIDED became SUBMITTED and REJECTED became RETURNED.

    SUBMITTED now means "went to the client on a transmittal", and no
    transmittal exists yet — so an item someone had ticked PROVIDED goes back
    to REQUIRED rather than claiming a submission that never happened. Its
    file and its provided_on stamp are kept, so it shows up as ready to send
    on the first transmittal. Asserting SUBMITTED here would be the very
    claim this change removes.
    """
    Item = apps.get_model("core", "HandoverItem")
    Item.objects.filter(status="PROVIDED").update(status="REQUIRED")
    Item.objects.filter(status="REJECTED").update(status="RETURNED")


def unrename_statuses(apps, schema_editor):
    Item = apps.get_model("core", "HandoverItem")
    Item.objects.filter(status="SUBMITTED").update(status="PROVIDED")
    Item.objects.filter(status="RETURNED").update(status="REJECTED")
    # REQUIRED is not reversed: which of them were once PROVIDED is not
    # recoverable, and guessing would be worse than leaving them owed.


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_remove_site_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoveritem',
            name='revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handoveritem',
            name='status',
            field=models.CharField(choices=[('REQUIRED', 'Required — not yet provided'), ('SUBMITTED', 'Submitted to the client'), ('ACCEPTED', 'Accepted by the client'), ('RETURNED', 'Returned for correction'), ('NOT_APPLICABLE', 'Not applicable')], default='REQUIRED', max_length=14),
        ),
        migrations.CreateModel(
            name='HandoverTransmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('ref', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — being assembled'), ('ISSUED', 'Issued to the client'), ('CLOSED', 'Closed — every document answered')], default='DRAFT', max_length=8)),
                ('subject', models.TextField(blank=True)),
                ('covering_note', models.TextField(blank=True)),
                ('addressed_to', models.CharField(blank=True, max_length=120)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('response_days', models.IntegerField(default=14)),
                ('response_due_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittals', to='core.handoverdossier')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='HandoverTransmittalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_COMMENTS', 'Approved with comments'), ('REJECTED', 'Rejected — resubmit')], max_length=22)),
                ('result_on', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('reply_ref', models.CharField(blank=True, max_length=80)),
                ('comments', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittal_lines', to='core.handoveritem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transmittal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.handovertransmittal')),
            ],
            options={
                'ordering': ['transmittal', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='handovertransmittal',
            constraint=models.UniqueConstraint(fields=('dossier', 'seq'), name='uniq_transmittal_seq_per_dossier'),
        ),
        migrations.AddConstraint(
            model_name='handovertransmittalline',
            constraint=models.UniqueConstraint(fields=('transmittal', 'item'), name='uniq_item_per_transmittal'),
        ),
        migrations.RunPython(rename_statuses, unrename_statuses),
    ]
