# Generated by Django 5.2.17 on 2026-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_handover_transmittals'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchargecorrection',
            name='drop_line_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
