# Generated by Django 5.2.17 on 2026-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_ipr_drop_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchargecorrection',
            name='line_amendments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
