# Generated by Django 5.2.17 on 2026-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleline',
            name='amended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleline',
            name='eta_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
