# Generated by Django 5.2.17 on 2026-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_scheduleline_eta_and_amended'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchargecorrection',
            name='new_lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
