# Generated by Django 5.2.17 on 2026-09-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_subcontract_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payable',
            name='payroll_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='core.payrollline'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DPR', 'Dpr'), ('TWS', 'Tws'), ('IR', 'Ir'), ('MAR', 'Mar'), ('SD', 'Sd'), ('MS', 'Ms'), ('MR', 'Mr'), ('GRN', 'Grn'), ('PR', 'Pr'), ('LM', 'Lm'), ('PO', 'Po'), ('DMA', 'Dma'), ('PYR', 'Pyr'), ('PV', 'Pv'), ('PMR', 'Pmr'), ('IPR', 'Ipr'), ('IRN', 'Irn'), ('SIN', 'Sin'), ('SCA', 'Sca'), ('SVC', 'Svc'), ('OBR', 'Obr'), ('PSC', 'Psc'), ('MTN', 'Mtn'), ('INC', 'Inc'), ('TBT', 'Tbt'), ('PTW', 'Ptw'), ('RAS', 'Ras'), ('HSI', 'Hsi'), ('ITP', 'Itp'), ('NCR', 'Ncr'), ('RFI', 'Rfi'), ('LTR', 'Ltr'), ('INS', 'Ins'), ('NTC', 'Ntc'), ('DLY', 'Dly'), ('EOT', 'Eot'), ('TR', 'Tr'), ('TDR', 'Tdr'), ('MXD', 'Mxd'), ('BBS', 'Bbs'), ('TWD', 'Twd'), ('MOC', 'Moc'), ('ABD', 'Abd')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tenderevent',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tender'),
        ),
    ]
