# Generated by Django 5.2.17 on 2026-09-10 16:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0230_tender_discount_and_provisional_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractagreement',
            name='basis',
            field=models.CharField(choices=[('MEASURED', 'Measured work'), ('DAYWORK', 'Day work (labour supply)')], default='MEASURED', max_length=10),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='subcontractvaluation',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subcontractvaluation',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcontractvaluation',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubcontractDayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ot_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rates', to='core.subcontractagreement')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.manpowercategory')),
            ],
            options={
                'ordering': ['job_category__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'job_category'), name='uniq_sca_day_rate')],
            },
        ),
        migrations.CreateModel(
            name='SubcontractWorkerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ot_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.employee')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.manpowercategory')),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_days', to='core.subcontractvaluation')),
            ],
            options={
                'ordering': ['job_category__sort_order', 'employee__emp_no'],
                'constraints': [models.UniqueConstraint(fields=('valuation', 'employee'), name='uniq_svc_worker_day')],
            },
        ),
    ]
