# Generated by Django 5.2.17 on 2026-09-12 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_subcontract_daywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sub_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='day_rate_divisor',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='friday_rate_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='subcontractagreement',
            name='ot_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subcontractworkerday',
            name='friday_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='subcontractworkerday',
            name='friday_rate_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='subcontractworkerday',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='SubcontractDayRate',
        ),
    ]
