# Generated by Django 5.2.17 on 2026-09-15 11:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_subcontract_extra_hours_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.attachment_path),
        ),
    ]
