# Generated by Django 5.2.17 on 2026-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_attachment_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('TENDERING', 'Tendering'), ('AWARDED', 'Awarded'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], default='TENDERING', max_length=10),
        ),
    ]
