# Generated by Django 5.2.17 on 2026-09-17 04:39

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Every existing run gets its reference in creation order per counter
    (site, or the combined USD run), the PRL counters are set to match, and
    every line is numbered within its run by employee number."""
    PayrollRun = apps.get_model("core", "PayrollRun")
    PayrollLine = apps.get_model("core", "PayrollLine")
    DocCounter = apps.get_model("core", "DocCounter")
    last = {}
    for run in PayrollRun.objects.order_by("id").select_related("site"):
        key = run.site_id
        n = last.get(key, 0) + 1
        last[key] = n
        code = run.site.code if run.site_id else "USD"
        run.ref = f"PRL-{code}-{n:03d}"
        run.save(update_fields=["ref"])
        for i, line in enumerate(
                PayrollLine.objects.filter(run=run)
                .order_by("employee__emp_no", "id"), 1):
            line.pay_no = i
            line.save(update_fields=["pay_no"])
    for site_id, n in last.items():
        c, _ = DocCounter.objects.get_or_create(doc_type="PRL", site_id=site_id)
        c.last_no = max(c.last_no, n)
        c.save(update_fields=["last_no"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_tender_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='pay_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.RunPython(backfill, noop),
    ]
