# Generated by Django 5.2.17 on 2026-09-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0237_payroll_run_ref_and_pay_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='cost_note',
            field=models.TextField(blank=True),
        ),
    ]
