# Generated by Django 5.2.17 on 2026-09-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_boq_item_cost_and_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='labour_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='labour_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
