# Generated by Django 5.2.17 on 2026-09-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_boq_item_labour_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqItemWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOUR', 'Labour'), ('PLANT', 'Plant'), ('SUBCONTRACT', 'Subcontract'), ('OTHER', 'Other')], default='MATERIAL', max_length=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('qty_expr', models.CharField(blank=True, max_length=80)),
                ('rate_expr', models.CharField(blank=True, max_length=80)),
                ('waste_expr', models.CharField(blank=True, max_length=40)),
                ('qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('waste_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workings', to='core.boqitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
