# Generated by Django 5.2.17 on 2026-09-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_tender_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdeduction',
            name='before_gst',
            field=models.BooleanField(default=False),
        ),
    ]
