# Generated by Django 5.2.17 on 2026-09-24 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_claim_deduction_before_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='costposting',
            name='book',
            field=models.CharField(choices=[('PROJECT', 'Project'), ('TRADING', 'Trading')], db_index=True, default='PROJECT', max_length=8),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_trading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('SIGNATORY', 'Signatory (Executive Director)'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('QS', 'Quantity Surveyor'), ('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('PA', "Personal Assistant — Director's Office"), ('SALES', 'Sales — trading inquiries, quotes and orders'), ('SALES_MANAGER', 'Sales Manager — authorises trading quotes and invoices')], max_length=20),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tin', models.CharField(blank=True, max_length=30)),
                ('business_reg_no', models.CharField(blank=True, max_length=40)),
                ('billing_address', models.TextField(blank=True)),
                ('island', models.TextField(blank=True)),
                ('vessels', models.TextField(blank=True)),
                ('contact_person', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='MVR', max_length=3)),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('gst_exempt', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
