# Generated by Django 5.2.17 on 2026-09-24 13:50

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_trading_foundations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=12, unique=True)),
                ('title', models.TextField()),
                ('inquiry_date', models.DateField()),
                ('received_via', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WHATSAPP', 'Whatsapp'), ('VISIT', 'Visit'), ('OTHER', 'Other')], default='EMAIL', max_length=10)),
                ('customer_ref', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('INQUIRY', 'Inquiry'), ('SOURCING', 'Sourcing'), ('PRICING', 'Pricing'), ('QUOTED', 'Quoted'), ('WON', 'Won'), ('LOST', 'Lost')], default='INQUIRY', max_length=10)),
                ('stage_since', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quote_valid_days', models.PositiveIntegerField(default=14)),
                ('payment_terms', models.TextField(blank=True)),
                ('delivery_terms', models.TextField(blank=True, default='Delivered to your vessel at Malé harbour')),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('freight_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_ref', models.CharField(blank=True, max_length=12)),
                ('po_number', models.TextField(blank=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_file', models.FileField(blank=True, null=True, upload_to=core.models.trading_po_path)),
                ('so_ref', models.CharField(blank=True, max_length=12)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_orders', to=settings.AUTH_USER_MODEL)),
                ('won_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('section', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('fx', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sell', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.supplier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.tradingorder')),
            ],
            options={
                'ordering': ['sr_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TradingQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AWAITING_AUTH', 'Awaiting Auth'), ('AUTHORISED', 'Authorised'), ('SUPERSEDED', 'Superseded'), ('WITHDRAWN', 'Withdrawn')], default='AWAITING_AUTH', max_length=14)),
                ('snapshot', models.JSONField(default=dict)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=core.models.trading_quote_path)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.tradingorder')),
            ],
            options={
                'ordering': ['order_id', 'revision'],
                'constraints': [models.UniqueConstraint(fields=('order', 'revision'), name='uniq_trading_quote_rev')],
            },
        ),
    ]
