# Generated by Django 5.2.17 on 2026-09-24 15:24

import django.db.models.deletion
from django.db import migrations, models


TRADING_HEADS = [
    ("TRD_COGS", "Trading — Cost of sales", 910),
    ("TRD_REVENUE", "Trading — Revenue", 900),
    ("TRD_OUTPUT_GST", "Output GST (payable)", 930),
    ("TRD_FREIGHT", "Trading — Freight & delivery", 920),
]


def seed_trading_heads(apps, schema_editor):
    """The trading book's own heads (TRADING_BUILD_BRIEF.md §5). Reached
    for by code; never offered in a project picker."""
    CostHead = apps.get_model("core", "CostHead")
    for code, name, order in TRADING_HEADS:
        if CostHead.objects.filter(code=code).exists():
            continue
        if CostHead.objects.filter(name=name).exists():
            CostHead.objects.filter(name=name).update(
                code=code, trading=True, is_system=True)
            continue
        CostHead.objects.create(code=code, name=name, sort_order=order,
                                trading=True, is_system=True)


def unseed(apps, schema_editor):
    CostHead = apps.get_model("core", "CostHead")
    CostHead.objects.filter(code__in=[c for c, _, _ in TRADING_HEADS],
                            postings__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0244_trading_sales_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='costhead',
            name='trading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importallocation',
            name='trading_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_allocations', to='core.tradingorder'),
        ),
        migrations.AddField(
            model_name='importorder',
            name='trading_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='core.tradingorder'),
        ),
        migrations.AddField(
            model_name='importorderline',
            name='trading_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipr_lines', to='core.tradingline'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='trading_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.tradingorder'),
        ),
        migrations.RunPython(seed_trading_heads, unseed),
    ]
