# Generated by Django 5.2.17 on 2026-09-24 17:24

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_trading_supply_leg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costposting',
            name='source',
            field=models.CharField(choices=[('PR', 'Pr'), ('PYR', 'Pyr'), ('PETTY_CASH', 'Petty Cash'), ('STAFF', 'Staff'), ('IPR', 'Ipr'), ('STORE_ISSUE', 'Store Issue'), ('FX', 'Fx'), ('STOCK_ADJ', 'Stock Adj'), ('SUBCONTRACT', 'Subcontract'), ('SALE', 'Sale')], max_length=12),
        ),
        migrations.CreateModel(
            name='TradingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DESPATCHED', 'Despatched'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('delivery_date', models.DateField()),
                ('vessel', models.TextField(blank=True)),
                ('jetty', models.TextField(blank=True, default='Malé harbour')),
                ('receiver', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('signed_copy', models.FileField(blank=True, null=True, upload_to=core.models.trading_dn_path)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=core.models.trading_dn_path)),
                ('cogs_mvr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('posting_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('despatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('despatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.tradingorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TradingDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost_mvr', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('lots', models.JSONField(blank=True, default=list)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.tradingdelivery')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='core.tradingline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TradingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=8)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('includes_freight', models.BooleanField(default=False)),
                ('charges', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField(default=dict)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=core.models.trading_inv_path)),
                ('posting_ids', models.JSONField(blank=True, default=list)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.tradingorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='tradingdelivery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.tradinginvoice'),
        ),
        migrations.CreateModel(
            name='TradingCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.TextField()),
                ('posting_ids', models.JSONField(blank=True, default=list)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.tradinginvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TradingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('receipt_date', models.DateField()),
                ('method', models.CharField(choices=[('TT', 'Telegraphic transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], default='TT', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.companybankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradingReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.tradinginvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.tradingreceipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
