# Generated by Django 5.2.17 on 2026-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_trading_delivery_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingline',
            name='spec',
            field=models.TextField(blank=True),
        ),
    ]
