# Generated by Django 5.2.17 on 2026-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_trading_line_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='extra_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='incoterm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='lead_time',
            field=models.TextField(blank=True),
        ),
    ]
