# Generated by Django 5.2.17 on 2026-09-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_trading_year_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinginvoice',
            name='advance_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='tradingreceiptline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_receipts', to='core.tradingorder'),
        ),
        migrations.AlterField(
            model_name='tradingreceiptline',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.tradinginvoice'),
        ),
    ]
