# Generated by Django 5.2.17 on 2026-09-25 10:34

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


RENTAL_HEADS = [
    ("RNT_REVENUE", "Rental — Revenue", 950),
    ("RNT_MAINTENANCE", "Rental — Maintenance & spares", 960),
    ("RNT_FUEL", "Rental — Fuel & running", 970),
    ("RNT_OPERATOR", "Rental — Operator wages", 980),
    ("RNT_INSURANCE", "Rental — Insurance & licences", 990),
    ("RNT_OUTPUT_GST", "Rental — Output GST (payable)", 995),
]


def seed_rental_heads(apps, schema_editor):
    """The rental book's own heads (MARINE_BUILD_BRIEF.md §4): reached for
    by code, kept out of every project picker."""
    CostHead = apps.get_model("core", "CostHead")
    for code, name, order in RENTAL_HEADS:
        if CostHead.objects.filter(code=code).exists():
            continue
        if CostHead.objects.filter(name=name).exists():
            CostHead.objects.filter(name=name).update(code=code, rental=True, is_system=True)
            continue
        CostHead.objects.create(code=code, name=name, sort_order=order,
                                rental=True, is_system=True)


def unseed(apps, schema_editor):
    CostHead = apps.get_model("core", "CostHead")
    CostHead.objects.filter(code__in=[c for c, _, _ in RENTAL_HEADS],
                            postings__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_trading_advances'),
    ]

    operations = [
        migrations.AddField(
            model_name='costhead',
            name='rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='costposting',
            name='book',
            field=models.CharField(choices=[('PROJECT', 'Project'), ('TRADING', 'Trading'), ('RENTAL', 'Rental')], db_index=True, default='PROJECT', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ENGINEER', 'Site Engineer'), ('SITE_ADMIN', 'Site Admin / Storekeeper'), ('PM', 'Project Manager'), ('HO_PURCHASING', 'HO Purchasing'), ('DIRECTOR', 'Sr PM / Director, Projects'), ('SIGNATORY', 'Signatory (Executive Director)'), ('FINANCE', 'Finance'), ('HO_HR', 'HO HR / Payroll'), ('QS', 'Quantity Surveyor'), ('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('PA', "Personal Assistant — Director's Office"), ('SALES', 'Sales — trading inquiries, quotes and orders'), ('SALES_MANAGER', 'Sales Manager — authorises trading quotes and invoices'), ('RENTAL', 'Rental — fleet, agreements and the daily register'), ('RENTAL_MANAGER', 'Rental Manager — rates, agreements and invoices')], max_length=20),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=30, unique=True)),
                ('fleet_no', models.CharField(blank=True, max_length=20)),
                ('vehicle_class', models.CharField(max_length=60)),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, max_length=60)),
                ('engine_no', models.CharField(blank=True, max_length=60)),
                ('chassis_no', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_HIRE', 'On Hire'), ('MAINTENANCE', 'Maintenance'), ('OFF_ROAD', 'Off Road'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=12)),
                ('photo', models.FileField(blank=True, null=True, upload_to=core.models.vehicle_photo_path)),
                ('rate_currency', models.CharField(default='MVR', max_length=3)),
                ('rate_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('operator_included', models.BooleanField(default=True)),
                ('operator_rate_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_charge_days', models.PositiveIntegerField(default=1)),
                ('fuel_basis', models.CharField(choices=[('WITH_FUEL', 'Fuel included in the rate'), ('WITHOUT_FUEL', 'Customer supplies fuel')], default='WITHOUT_FUEL', max_length=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('hour_meter', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee')),
            ],
            options={
                'ordering': ['fleet_no', 'reg_no'],
            },
        ),
        migrations.AddField(
            model_name='costposting',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REGISTRATION', 'Registration'), ('INSURANCE', 'Insurance'), ('ROADWORTHINESS', 'Roadworthiness'), ('PERMIT', 'Permit / licence'), ('OTHER', 'Other')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.vehicle_doc_path)),
                ('notes', models.TextField(blank=True)),
                ('alert_level', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vehicle')),
            ],
            options={
                'ordering': ['vehicle_id', 'kind', '-expires_on'],
            },
        ),
        migrations.RunPython(seed_rental_heads, unseed),
    ]
