# Generated by Django 5.2.17 on 2026-09-25 10:58

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_rental_foundations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly, in arrears'), ('ON_COMPLETION', 'On completion of the hire')], default='MONTHLY', max_length=14)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mobilisation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('demobilisation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('site_location', models.TextField(blank=True)),
                ('customer_rep', models.TextField(blank=True)),
                ('customer_rep_phone', models.TextField(blank=True)),
                ('customer_po', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('extra_terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=core.models.agreement_path)),
                ('signed_copy', models.FileField(blank=True, null=True, upload_to=core.models.agreement_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='core.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RentalAgreementVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_daily', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operator_included', models.BooleanField(default=True)),
                ('operator_rate_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.rentalagreement')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_lines', to='core.vehicle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RentalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='DRAFT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.rentalagreement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HireLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('WORKED', 'Worked'), ('STANDBY', 'Standby (billable)'), ('BREAKDOWN', 'Breakdown'), ('OFF_HIRE', 'Off hire')], default='WORKED', max_length=10)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_via', models.CharField(blank=True, max_length=8)),
                ('signed_register', models.FileField(blank=True, null=True, upload_to=core.models.register_path)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register', to='core.rentalagreement')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register', to='core.rentalagreementvehicle')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days', to='core.rentalinvoice')),
            ],
            options={
                'ordering': ['date', 'line_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentalagreementvehicle',
            constraint=models.UniqueConstraint(fields=('agreement', 'vehicle'), name='uniq_agreement_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='hirelog',
            constraint=models.UniqueConstraint(fields=('line', 'date'), name='uniq_hirelog_line_day'),
        ),
    ]
