# Generated by Django 5.2.17 on 2026-09-25 11:41

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_rental_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinvoice',
            name='charges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='currency',
            field=models.CharField(default='MVR', max_length=3),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rental_invoices', to='core.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.models.rental_inv_path),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='period_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='period_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='posting_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=8),
        ),
        migrations.CreateModel(
            name='RentalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('receipt_date', models.DateField()),
                ('method', models.CharField(choices=[('TT', 'Telegraphic transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], default='TT', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.companybankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_receipts', to='core.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RentalReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.rentalinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.rentalreceipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
