# Generated by Django 5.2.17 on 2026-09-25 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_rental_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('SERVICE', 'Scheduled service'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('TYRES', 'Tyres / tracks'), ('OTHER', 'Other')], default='REPAIR', max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('opened_on', models.DateField()),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('hour_meter_at', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('work_done', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('downtime_days', models.PositiveIntegerField(blank=True, null=True)),
                ('next_service_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.vehicle')),
            ],
            options={
                'ordering': ['-opened_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='maintenance_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='core.maintenancejob'),
        ),
    ]
