# Generated by Django 5.2.17 on 2026-09-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_vehicle_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='project_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_records', to='core.site'),
        ),
    ]
