# Generated by Django 5.2.17 on 2026-09-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_customer_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='clauses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
