# Generated by Django 5.2.17 on 2026-09-26 06:30

import django.db.models.deletion
from django.db import migrations, models


def _fill_customer(apps, schema_editor):
    TradingInvoice = apps.get_model("core", "TradingInvoice")
    for inv in TradingInvoice.objects.filter(customer__isnull=True, order__isnull=False).select_related("order"):
        inv.customer_id = inv.order.customer_id
        inv.save(update_fields=["customer"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_agreement_clauses'),
    ]

    operations = [
        # (data step appended below: every existing invoice takes its
        # order's customer)
        migrations.AddField(
            model_name='tradinginvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_invoices', to='core.customer'),
        ),
        migrations.AddField(
            model_name='tradinginvoice',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tradinginvoice',
            name='historic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradinginvoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.tradingorder'),
        ),
            migrations.RunPython(_fill_customer, migrations.RunPython.noop),
    ]
