# Generated by Django 5.2.17 on 2026-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_trading_historic_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
