# Generated by Django 5.2.17 on 2026-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0258_user_extra_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_instance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
