# Generated by Django 5.2.17 on 2026-09-29 10:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_user_home_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineOffence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('SAFETY', 'Safety'), ('DISCIPLINARY', 'Disciplinary'), ('OTHER', 'Other')], default='SAFETY', max_length=14)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=24, unique=True)),
                ('category', models.CharField(choices=[('SAFETY', 'Safety'), ('DISCIPLINARY', 'Disciplinary'), ('OTHER', 'Other')], max_length=14)),
                ('violation_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidence', models.FileField(blank=True, null=True, upload_to=core.models.fine_evidence_path)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting PM approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('deduct_year', models.PositiveIntegerField(blank=True, null=True)),
                ('deduct_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carried_note', models.CharField(blank=True, max_length=200)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='core.employee')),
                ('offence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='core.fineoffence')),
                ('payroll_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='core.payrollline')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_fines', to='core.site')),
            ],
            options={
                'ordering': ['-violation_date', '-id'],
                'indexes': [models.Index(fields=['status', 'deduct_year', 'deduct_month'], name='core_worker_status_78a081_idx'), models.Index(fields=['employee', 'status'], name='core_worker_employe_4e72f9_idx')],
            },
        ),
    ]
