# Generated by Django 5.2.17 on 2026-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0260_worker_fines'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tracked_tool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolasset',
            name='source',
            field=models.CharField(choices=[('MOBILISATION', 'Mobilisation'), ('GRN', 'Received (GRN)'), ('MANUAL', 'Added manually'), ('STOCK', 'Moved from stock')], default='MANUAL', max_length=12),
        ),
    ]
