# Generated by Django 5.2.17 on 2026-10-02 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_item_tracked_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('MANUAL', 'Journal'), ('OPENING', 'Opening balances'), ('REVERSAL', 'Reversal'), ('AUTO', 'Posted from operations')], default='MANUAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=8)),
                ('memo', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='core.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('BANK', 'Bank'), ('AR', 'Accounts receivable'), ('OTHER_CURRENT_ASSET', 'Other current assets'), ('FIXED_ASSET', 'Fixed assets'), ('OTHER_ASSET', 'Other assets'), ('AP', 'Accounts payable'), ('CREDIT_CARD', 'Credit card'), ('OTHER_CURRENT_LIABILITY', 'Other current liabilities'), ('LONG_TERM_LIABILITY', 'Long term liabilities'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('COGS', 'Cost of goods sold'), ('EXPENSE', 'Expenses'), ('OTHER_INCOME', 'Other income'), ('OTHER_EXPENSE', 'Other expenses')], max_length=24)),
                ('is_group', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('system_key', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account', to='core.companybankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.ledgeraccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('amount_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('party', models.CharField(blank=True, max_length=160)),
                ('cost_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.costhead')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.project')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.site')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.ledgeraccount')),
            ],
            options={
                'ordering': ['entry_id', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'date'], name='core_journa_status_f83252_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='core_journa_source__834c01_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ref', ''), _negated=True), fields=('ref',), name='uniq_journal_ref'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key', ''), _negated=True), fields=('system_key',), name='uniq_ledger_system_key'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='core_journa_account_3601e8_idx'),
        ),
    ]
