# Generated by Django 5.2.17 on 2026-10-02 12:37

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_ledger_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('MANUAL', 'Journal'), ('OPENING', 'Opening balances'), ('REVERSAL', 'Reversal'), ('AUTO', 'Posted from operations'), ('TXN', 'Transaction')], default='MANUAL', max_length=10),
        ),
        migrations.CreateModel(
            name='LedgerTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=8)),
                ('date', models.DateField()),
                ('party', models.CharField(blank=True, max_length=160)),
                ('party_tin', models.CharField(blank=True, max_length=40)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('memo', models.TextField(blank=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_mvr', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('tax_invoice_no', models.CharField(blank=True, max_length=60)),
                ('tax_invoice_date', models.DateField(blank=True, null=True)),
                ('tax_invoice_held', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=core.models.ledger_txn_path)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='core.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.journalentry')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.ledgeraccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTxnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('gst_treatment', models.CharField(choices=[('NONE', 'No GST'), ('STANDARD', 'Standard rated'), ('ZERO', 'Zero rated'), ('EXEMPT', 'Exempt'), ('OUT_OF_SCOPE', 'Out of scope')], default='NONE', max_length=14)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.ledgeraccount')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.project')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.site')),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.ledgertxn')),
            ],
            options={
                'ordering': ['txn_id', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgertxn',
            index=models.Index(fields=['type', 'date'], name='core_ledger_type_672e41_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertxn',
            index=models.Index(fields=['account', 'date'], name='core_ledger_account_e8073d_idx'),
        ),
    ]
