# Generated by Django 5.2.17 on 2026-10-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_ledger_txns'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTxnApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_mvr', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'ordering': ['payment_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ledgertxn',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgertxn',
            name='is_opening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ledgertxn',
            name='type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('BILL', 'Bill'), ('BILL_PAY', 'Bill payment'), ('INVOICE', 'Sales invoice'), ('RECEIPT', 'Payment received')], max_length=10),
        ),
        migrations.CreateModel(
            name='LedgerParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=8)),
                ('name', models.CharField(max_length=160)),
                ('tin', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ledgertxn',
            name='party_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='core.ledgerparty'),
        ),
        migrations.AddIndex(
            model_name='ledgertxn',
            index=models.Index(fields=['party_ref', 'type'], name='core_ledger_party_r_4b4839_idx'),
        ),
        migrations.AddField(
            model_name='ledgertxnapply',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied', to='core.ledgertxn'),
        ),
        migrations.AddField(
            model_name='ledgertxnapply',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='core.ledgertxn'),
        ),
        migrations.AddConstraint(
            model_name='ledgerparty',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='ledger_party_kind_name'),
        ),
    ]
