# Generated by Django 5.2.17 on 2026-10-02 13:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_ledger_bills_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'In progress'), ('DONE', 'Reconciled')], default='DRAFT', max_length=6)),
                ('statement_file', models.FileField(blank=True, null=True, upload_to=core.models.bank_statement_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='core.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='cleared_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='core.bankreconciliation'),
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('matched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalline')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='core.bankreconciliation')),
            ],
            options={
                'ordering': ['reconciliation_id', 'line_no'],
            },
        ),
    ]
