# Generated by Django 5.2.17 on 2026-10-02 13:42

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0265_bank_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.ledger_import_path)),
                ('filename', models.CharField(max_length=200)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
                ('total_mvr', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ledgertxn',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txns', to='core.ledgerimport'),
        ),
    ]
