# Generated by Django 5.2.17 on 2026-10-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_ledger_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='costhead',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ledgeraccount'),
        ),
    ]
