# Generated by Django 5.2.17 on 2026-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0267_costhead_ledger_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertxn',
            name='outside_planet',
            field=models.BooleanField(default=False),
        ),
    ]
