# Generated by Django 5.2.17 on 2026-10-02 17:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_rent_head(apps, schema_editor):
    """The cost head a rent contract posts under unless another is chosen.
    Reached for by code; the name is the owner's to change."""
    CostHead = apps.get_model("core", "CostHead")
    if CostHead.objects.filter(code="RENT").exists():
        return
    named = CostHead.objects.filter(name__iexact="Rent").first()
    if named:
        named.code, named.is_system = "RENT", True
        named.save(update_fields=["code", "is_system"])
        return
    CostHead.objects.create(code="RENT", name="Rent", sort_order=85,
                            is_system=True)


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_ledgertxn_outside_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costposting',
            name='source',
            field=models.CharField(choices=[('PR', 'Pr'), ('PYR', 'Pyr'), ('PETTY_CASH', 'Petty Cash'), ('STAFF', 'Staff'), ('IPR', 'Ipr'), ('STORE_ISSUE', 'Store Issue'), ('FX', 'Fx'), ('STOCK_ADJ', 'Stock Adj'), ('SUBCONTRACT', 'Subcontract'), ('SALE', 'Sale'), ('RENT', 'Rent')], max_length=12),
        ),
        migrations.AlterField(
            model_name='payable',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='core.document'),
        ),
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('OFFICE', 'Office'), ('ACCOMMODATION', 'Staff accommodation'), ('WAREHOUSE', 'Warehouse / store'), ('LAND', 'Land / yard'), ('VEHICLE', 'Vehicle / vessel'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], default='OFFICE', max_length=14)),
                ('landlord', models.CharField(max_length=160)),
                ('landlord_tin', models.CharField(blank=True, max_length=40)),
                ('landlord_contact', models.CharField(blank=True, max_length=200)),
                ('payee_account', models.TextField(blank=True)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=12)),
                ('in_advance', models.BooleanField(default=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dues_from', models.DateField()),
                ('lead_days', models.PositiveSmallIntegerField(default=7)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agreement', models.FileField(blank=True, null=True, upload_to=core.models.rent_agreement_path)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.costhead')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_contracts', to='core.site')),
            ],
            options={
                'ordering': ['ref'],
            },
        ),
        migrations.CreateModel(
            name='RentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('RAISED', 'Due'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='RAISED', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_ref', models.CharField(blank=True, max_length=120)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dues', to='core.rentcontract')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract_id', 'period_start'],
            },
        ),
        migrations.AddField(
            model_name='costposting',
            name='rent_due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_postings', to='core.rentdue'),
        ),
        migrations.AddField(
            model_name='payable',
            name='rent_due',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='core.rentdue'),
        ),
        migrations.AddIndex(
            model_name='rentdue',
            index=models.Index(fields=['contract', 'period_start'], name='core_rentdu_contrac_39ca44_idx'),
        ),
        migrations.RunPython(seed_rent_head, unseed),
    ]
