# Generated by Django 5.2.17 on 2026-10-03 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


HEADS = [("TELECOM", "Telephone & internet", 86),
         ("UTILITIES", "Electricity & water", 87)]


def seed_heads(apps, schema_editor):
    """The cost heads a phone or utility account posts under unless another
    is chosen. Reached for by code; the names are the owner's to change."""
    CostHead = apps.get_model("core", "CostHead")
    for code, name, order in HEADS:
        if CostHead.objects.filter(code=code).exists():
            continue
        named = CostHead.objects.filter(name__iexact=name).first()
        if named:
            named.code, named.is_system = code, True
            named.save(update_fields=["code", "is_system"])
            continue
        CostHead.objects.create(code=code, name=name, sort_order=order,
                                is_system=True)


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_rent_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costposting',
            name='source',
            field=models.CharField(choices=[('PR', 'Pr'), ('PYR', 'Pyr'), ('PETTY_CASH', 'Petty Cash'), ('STAFF', 'Staff'), ('IPR', 'Ipr'), ('STORE_ISSUE', 'Store Issue'), ('FX', 'Fx'), ('STOCK_ADJ', 'Stock Adj'), ('SUBCONTRACT', 'Subcontract'), ('SALE', 'Sale'), ('RENT', 'Rent'), ('UTILITY', 'Utility')], max_length=12),
        ),
        migrations.CreateModel(
            name='BillAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('provider', models.CharField(max_length=120)),
                ('provider_tin', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('MOBILE', 'Mobile'), ('TELEPHONE', 'Telephone'), ('INTERNET', 'Internet'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('TV', 'Cable TV'), ('OTHER', 'Other')], max_length=12)),
                ('account_no', models.CharField(max_length=60)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.costhead')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_accounts', to='core.site')),
            ],
            options={
                'ordering': ['provider', 'account_no'],
            },
        ),
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('bill_no', models.CharField(blank=True, max_length=60)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(default='MVR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('RAISED', 'To pay'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='RAISED', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_ref', models.CharField(blank=True, max_length=120)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.billaccount')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period', 'account_id'],
            },
        ),
        migrations.AddField(
            model_name='costposting',
            name='bill_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_postings', to='core.billcharge'),
        ),
        migrations.AddField(
            model_name='payable',
            name='bill_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='core.billcharge'),
        ),
        migrations.AddConstraint(
            model_name='billaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'account_no'), name='bill_account_unique'),
        ),
        migrations.AddIndex(
            model_name='billcharge',
            index=models.Index(fields=['account', 'period'], name='core_billch_account_5a172c_idx'),
        ),
        migrations.AddIndex(
            model_name='billcharge',
            index=models.Index(fields=['status', 'due_date'], name='core_billch_status_b00636_idx'),
        ),
        migrations.RunPython(seed_heads, unseed),
    ]
