# Generated by Django 5.2.17 on 2026-10-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_bill_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcharge',
            name='deduct_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billcharge',
            name='deduct_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billcharge',
            name='recover_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billcharge',
            name='recover_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_recoveries', to='core.employee'),
        ),
    ]
