# Generated by Django 5.2.17 on 2026-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_bill_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaccount',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billaccount',
            name='prepaid',
            field=models.BooleanField(default=False),
        ),
    ]
