# Generated by Django 5.2.17 on 2026-10-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_bill_prepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='round_to',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
