# Generated by Django 5.2.17 on 2026-10-04 11:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0273_payrollrun_round_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('FINANCIAL', 'Financial statements audit'), ('TAX', 'Tax audit'), ('OTHER', 'Other audit')], default='FINANCIAL', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('auditor', models.CharField(max_length=160)),
                ('partner', models.CharField(blank=True, max_length=160)),
                ('auditor_contact', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('DRAFT', 'Draft received'), ('COMPLETED', 'Report issued'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, choices=[('UNMODIFIED', 'Unmodified (clean)'), ('QUALIFIED', 'Qualified'), ('ADVERSE', 'Adverse'), ('DISCLAIMER', 'Disclaimer of opinion')], max_length=12)),
                ('fee_currency', models.CharField(default='MVR', max_length=3)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENGAGEMENT', 'Engagement letter'), ('DRAFT', 'Draft report'), ('REPORT', 'Audit report (final)'), ('MANAGEMENT', 'Management letter'), ('REPRESENTATION', 'Representation letter'), ('INVOICE', "Auditor's invoice"), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('file', models.FileField(upload_to=core.models.external_audit_path)),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.externalaudit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
