# Generated by Django 5.2.17 on 2026-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0274_external_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='balance_before_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='advance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
