# Generated by Django 5.2.17 on 2026-10-05 14:35

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0275_purchase_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='snagitem',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major — holds the handover')], default='MINOR', max_length=5),
        ),
        migrations.AddField(
            model_name='snagitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snags', to='core.projectunit'),
        ),
        migrations.CreateModel(
            name='UnitHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFFERED', 'Offered for inspection'), ('INSPECTED', 'Inspected'), ('HANDED_OVER', 'Handed over')], default='OFFERED', max_length=12)),
                ('certificate_no', models.CharField(blank=True, max_length=30)),
                ('offered_on', models.DateField()),
                ('percent_at_offer', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proposed_inspection', models.DateField(blank=True, null=True)),
                ('inspected_on', models.DateField(blank=True, null=True)),
                ('client_attendees', models.TextField(blank=True)),
                ('our_attendees', models.TextField(blank=True)),
                ('inspection_notes', models.TextField(blank=True)),
                ('handed_over_on', models.DateField(blank=True, null=True)),
                ('client_signatory', models.CharField(blank=True, max_length=120)),
                ('client_position', models.CharField(blank=True, max_length=120)),
                ('signed_copy', models.FileField(blank=True, null=True, upload_to=core.models.unit_handover_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='core.projectunit')),
            ],
        ),
    ]
