# Generated by Django 5.2.17 on 2026-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_unit_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='site_split',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
