# Generated by Django 5.2.17 on 2026-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0278_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdeduction',
            name='kind',
            field=models.CharField(choices=[('BACK_CHARGE', 'Back charge'), ('WITHHELD', 'Amount withheld')], default='BACK_CHARGE', max_length=12),
        ),
    ]
