# Generated by Django 5.2.17 on 2026-10-10 16:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0279_claim_withheld'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('NO_SHOW', 'No show — not in camp / not found'), ('PERSONAL', 'Personal or family matter'), ('TRAVEL', 'Travelling'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='medication',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=12)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('count', models.IntegerField()),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=24, unique=True)),
                ('reported_on', models.DateField()),
                ('complaint', models.CharField(choices=[('UNKNOWN', 'Not yet recorded'), ('FEVER', 'Fever / flu-like'), ('DENGUE', 'Suspected dengue'), ('RESPIRATORY', 'Cough / respiratory'), ('STOMACH', 'Diarrhoea / vomiting / stomach'), ('SKIN', 'Skin / rash'), ('HEAT', 'Heat illness'), ('INJURY', 'Injury'), ('PAIN', 'Pain (back, joint, tooth, head)'), ('OTHER', 'Other')], default='UNKNOWN', max_length=12)),
                ('symptoms', models.TextField(blank=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('red_flag', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('REPORT', 'Reported on site'), ('ATTENDANCE', 'Marked sick on attendance'), ('INCIDENT', 'From an HSE incident')], default='REPORT', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('fit_on', models.DateField(blank=True, null=True)),
                ('light_duties', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_cases', to='core.employee')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_cases', to='core.safetyincident')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_cases', to='core.site')),
            ],
            options={
                'ordering': ['-reported_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FIRST_AID', 'First aid / OTC medicine on site'), ('RESTED', 'Rested in camp / sick bay'), ('RECHECK', 'Checked again (evening / next morning)'), ('DOCTOR', 'Seen resort doctor / nearest health centre'), ('MALE', 'Referred to Malé'), ('EVACUATED', 'Emergency evacuation'), ('ADMITTED', 'Admitted'), ('REPORT', "Doctor's report / prescription / certificate"), ('CLEARED', 'Cleared by doctor to return'), ('FOLLOW_UP', 'Follow-up check after return'), ('NOTE', 'Note')], max_length=10)),
                ('at', models.DateTimeField()),
                ('detail', models.TextField(blank=True)),
                ('facility', models.CharField(blank=True, max_length=160)),
                ('escort', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.healthcase')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HealthFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.health_file_path)),
                ('file_name', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.healthcase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMedicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focal_point_backup', models.CharField(blank=True, max_length=120)),
                ('hotline', models.CharField(blank=True, max_length=40)),
                ('hse_lead', models.CharField(blank=True, max_length=120)),
                ('first_aiders', models.TextField(blank=True)),
                ('nearest_health_centre', models.TextField(blank=True)),
                ('travel_time', models.CharField(blank=True, max_length=80)),
                ('resort_clinic', models.TextField(blank=True)),
                ('male_hospitals', models.TextField(blank=True)),
                ('boat_arrangement', models.TextField(blank=True)),
                ('sick_bay', models.TextField(blank=True)),
                ('emergency_contacts', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focal_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_plan', to='core.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='healthcase',
            index=models.Index(fields=['site', 'reported_on'], name='core_health_site_id_90e70a_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcase',
            index=models.Index(fields=['employee', 'reported_on'], name='core_health_employe_370108_idx'),
        ),
    ]
